Ordeal Pets 1.1
vlggms/lobotomy-corp13 pull request #1020
Opened 2023-06-02 02:33 UTC by InsightfulParasite

## About The Pull Request
Makes ordeal pets more fleshed out and useful.
Still its a big responsibility to own a pet so you should consider their strengths and what could obliterate them before bringing them here.
Amber and Crimson Ordeal Pet Crafting
Crimson will now do a little trick when touched with a bare hand. This will restore 5 sanity to everyone in range. This is more helpful for when your in a department recovering your sanity.
Green can now have a flashlight attached to them.

## Why It's Good For The Game
Fleshes out ordeal pets and makes them less janky. Not a important PR.

## Changelog
:cl:
tweak: Ordeal Pets Amber, Green, and Crimson.
/:cl:

2023-06-28 20:24 UTC, Kitsunemitsu approved these changes
Looks good to me.

2023-07-04 20:03 UTC, LanceSmites328 requested changes

2023-07-31 20:15 UTC, LanceSmites328 approved these changes

2023-08-01 20:10 UTC, LanceSmites328 approved these changes

2023-08-01 20:10 UTC, merged