adds god of the seasons
vlggms/lobotomy-corp13 pull request #1048
Opened 2023-06-13 03:55 UTC by Coxswain-Navigator

## About The Pull Request
Adds a new ALEPH with a ton of features.

## Why It's Good For The Game
We have an ALEPH shortage

## Changelog
:cl:
add: Added god of the seasons
/:cl:

2023-07-08 04:07 UTC, LanceSmites328 requested changes

2023-07-08 04:07 UTC, LanceSmites328 commented on code/modules/mob/living/simple_animal/abnormality/aleph/seasons.dm
> +		SLEEP_CHECK_DEATH(1)
```suggestion
	FireLine(turfs)
	turfs = LineTarget(-20, range, at)
	FireLine(turfs)
	turfs = LineTarget(0, range, at)
	FireLine(turfs)
	turfs = LineTarget(20, range, at)
	FireLine(turfs)
	turfs = LineTarget(40, range, at)
	FireLine(turfs)

/mob/living/simple_animal/hostile/abnormality/seasons/proc/LineTarget(offset, range, atom/at = target)
	set waitfor = FALSE
	if(!at)
		return
	var/turf/T = get_ranged_target_turf_direct(src, at, range, offset)
	return (getline(src, T) - get_turf(src))

/mob/living/simple_animal/hostile/abnormality/seasons/proc/FireLine(list/turfs)
	set waitfor = FALSE
	var/attacktype = breaching_stats[current_season][5]
	var/list/hit_list = list()
	for(var/turf/T in turfs)
		if(istype(T, /turf/closed))
			break
		new attacktype(T)
		for(var/mob/living/L in T.contents)
			if(L in hit_list || istype(L, type))
				continue
			hit_list += L
			L.apply_damage(cone_attack_damage, melee_damage_type, null, L.run_armor_check(null, melee_damage_type), spread_damage = TRUE)
			to_chat(L, "<span class='userdanger'>You have been hit by [src]'s breath attack!</span>")
			if(ishuman(L))
				Finisher(L)
		SLEEP_CHECK_DEATH(1)
```

2023-07-08 04:07 UTC, LanceSmites328 commented on code/modules/mob/living/simple_animal/abnormality/aleph/seasons.dm
> +		SLEEP_CHECK_DEATH(1)
`set waitfor = FALSE` should be used over INVOKE_ASYNC in cases where INVOKE_ASYNC is the only way they're meant to be called, as INVOKE_ASYNC more or less runs the proc with `set waitfor = FALSE`

2023-07-08 04:07 UTC, LanceSmites328 commented on code/modules/paperwork/records/info/aleph.dm
> +		"When the work result was bad, the Qliphoth counter decreased by one.")
Not true if it's small.

2023-07-08 04:35 UTC, Coxswain-Navigator commented on code/game/objects/items/ego_weapons/aleph.dm
> +	RegisterSignal(SSdcs, COMSIG_GLOB_SEASON_CHANGE, .proc/Transform)
I'm not really the right person to ask this question, I know little about performance impacts in byond, unfortunately.

2023-07-08 04:36 UTC, Coxswain-Navigator commented on code/modules/mob/living/simple_animal/abnormality/aleph/seasons.dm
> +			return chance + 50
30 is out of the question, this is specifically to make it so that the WAW form can be worked at with WAW attributes. I can just make it 45 instead.

2023-07-08 04:38 UTC, Coxswain-Navigator commented on code/modules/mob/living/simple_animal/abnormality/aleph/seasons.dm
> +	SSweather.run_weather(new_weather)
I think storing it locally makes it a lot more readable, and as I mentioned earlier I don't know how it affects performance.

2023-07-08 04:39 UTC, Coxswain-Navigator commented on code/modules/mob/living/simple_animal/abnormality/aleph/seasons.dm
> +	SSweather.run_weather(new_weather)
Oh on the topic of the legacy var, I may end up keeping it. I'll look at the feasibility of removing it.

2023-07-08 05:46 UTC, Coxswain-Navigator commented on code/modules/mob/living/simple_animal/abnormality/aleph/seasons.dm
> +	fear_level = WAW_LEVEL
Intended

2023-07-08 05:46 UTC, Coxswain-Navigator commented on code/modules/mob/living/simple_animal/abnormality/aleph/seasons.dm
> +	fear_level = WAW_LEVEL
Maybe.

2023-07-08 05:50 UTC, Coxswain-Navigator commented on code/modules/mob/living/simple_animal/abnormality/aleph/seasons.dm
> +	damage_coeff = new_damage_coeff.Copy()
I think doing this caused a failure in linters? I could be wrong

2023-07-08 06:10 UTC, Coxswain-Navigator commented on code/game/objects/items/ego_weapons/aleph.dm
> +	RegisterSignal(SSdcs, COMSIG_GLOB_SEASON_CHANGE, .proc/Transform)
However, using a local variable does make it a whole lot more readable.

2023-07-08 19:13 UTC, LanceSmites328 commented on code/modules/mob/living/simple_animal/abnormality/aleph/seasons.dm
> +	damage_coeff = new_damage_coeff.Copy()
Probably due to it not recognizing the indexes as Lists, fair enough.

2023-07-15 07:33 UTC, Kitsunemitsu requested changes
See Comment,
Applying Headcoder's Do not merge until this is resolved.

2023-07-15 07:33 UTC, Kitsunemitsu commented on code/modules/paperwork/records/info/aleph.dm
> +		"When the abnormality first appeared in the facility, it appeared in a mostly harmless, diminutive state which is designated with a WAW risk level. At this stage, any work result causes a drop in Q
Pick, Waw or Aleph. No fence sitting.

2023-07-17 17:44 UTC, LanceSmites328 submitted a review, later dismissed
Giving approval and asking for @Kitsunemitsu to remove label, or permission to.

2023-07-18 00:58 UTC, LanceSmites328 commented
![image](https://github.com/vlggms/lobotomy-corp13/assets/61567407/e1e50e6c-6a21-4a7b-b039-96881a19407c)

2023-08-01 20:16 UTC, LanceSmites328 approved these changes

2023-08-01 20:18 UTC, merged