Adds Butcherable Ordeals
vlggms/lobotomy-corp13 pull request #107
Opened 2022-08-05 02:43 UTC by EternityCoffee

Adds three different meats and gives the ability to butcher sweepers, the indigo midnight, amber dusk, and violet dawn.

Changelog
:cl:
add: Added three different meats that can be obtained by butchering certain ordeals
code: added butchering to sweepers, indigo midnight, amber dusk, and violet dawn.
/:cl:

2022-08-05 03:45 UTC, ilikesaying commented
finally, ordealburger

2022-08-06 12:03 UTC, EgorDinamit commented on code/modules/mob/living/simple_animal/hostile/ordeal/amber.dm
> +	butcher_results = list(/obj/item/food/meat/slab/human/mutant/worm = 2, /obj/item/food/meat/slab/human/mutant/worm = 3)
```suggestion
	butcher_results = list(/obj/item/food/meat/slab/human/mutant/worm = 3)
```

2022-08-06 12:03 UTC, EgorDinamit commented on code/modules/mob/living/simple_animal/hostile/ordeal/indigo.dm
> +	butcher_results = list(/obj/item/food/meat/slab/human/mutant/sweeper = 2, /obj/item/food/meat/slab/human/mutant/sweeper = 1)
```suggestion
	butcher_results = list(/obj/item/food/meat/slab/human/mutant/sweeper = 2)
```

2022-08-06 12:03 UTC, EgorDinamit commented on code/modules/mob/living/simple_animal/hostile/ordeal/indigo.dm
> +	butcher_results = list(/obj/item/food/meat/slab/human/mutant/sweeper = 3, /obj/item/food/meat/slab/human/mutant/sweeper = 4)
```suggestion
	butcher_results = list(/obj/item/food/meat/slab/human/mutant/sweeper = 4)
```

2022-08-06 12:04 UTC, EgorDinamit requested changes
Change case of the Ordeal_butchery.dmi
And is there any reason for it being a new file instead of putting it into food.dmi?

2022-08-07 00:28 UTC, merged