EGO Resprite, Adds Syrinx.
vlggms/lobotomy-corp13 pull request #1090
Opened 2023-06-26 18:37 UTC by Kitsunemitsu

## About The Pull Request
Adds some outstanding EGO resprites, and adds in syrinx

## Changelog
:cl:
add: Added syrinx gun
tweak: resprited old EGO sprites
/:cl:

2023-06-26 19:37 UTC, dsmith328 approved these changes
Keep me up to date on funny SFX for Syrinx

2023-06-26 19:39 UTC, dsmith328 requested changes

2023-06-26 19:39 UTC, dsmith328 commented on icons/mob/clothing/ego_gear/suit.dmi
Bayard Office Suit unnamed

2023-06-26 19:39 UTC, dsmith328 commented on icons/obj/clothing/ego_gear/suits.dmi
Same

2023-06-26 19:39 UTC, dsmith328 commented on icons/obj/ego_weapons.dmi
Mimicry Scythe but not in hand?

2023-06-26 19:41 UTC, Kitsunemitsu commented on icons/obj/ego_weapons.dmi
shiiiiit I will change that

2023-07-08 06:03 UTC, LanceSmites328 approved these changes

2023-07-08 06:03 UTC, merged