reworks golden apple
vlggms/lobotomy-corp13 pull request #1140
Opened 2023-07-13 11:38 UTC by vampirebat74

## About The Pull Request

What it says on the tin. This PR should complete the original vision I had when creating this abnormality. This is mainly through changing the core mechanics regarding the buff golden sheen:

- Golden sheen now restores half of what it used to, from 1 HP/SP to 0.5 HP/SP per tick.
- The maximum possible stacks of golden sheen has been elevated from 3 (which was impossible to obtain) to 5.
- The chemical "ambrosia" found within the abnormality's butcher return will now apply golden sheen stacks, rather than healing the user directly.

At best, the maximum possible healing at 2.5 HP/SP tick is higher than it was before, but it requires either suppressing the abnormality (possibly multiple times) or utilizing the abnochem system.

This pull request also buffs the first breaching form of the abnormality. It will now emit a healing pulse every 30 seconds that applies golden sheen to itself and nearby entities with the same faction, namely abnormalities. Since golden sheen expires within a minute, it will not be refreshed unless the targets remain in close proximity. Just like it would for players, this buff can stack up to five times. The second form lacks this ability.

Additionally, some visual effects have been added to targets who've been killed by the maggot DoT effect from its second form.

## Why It's Good For The Game

This was the original plan for the abnormality, and its first form is currently considered too weak. It may also allow the abnormality to serve as a healer role in PVP situations such as playable abnormalities and R. Corp CM.

## Changelog
:cl:
tweak: abnochem enabled for golden apple, the abnormality can now heal others in combat.
code: minor changes to the subject's life ticks, few procs cleaned up.
/:cl:

2023-07-13 21:28 UTC, Kitsunemitsu commented
Concept Wise, I approve.
I'll check out the code in a bit

2023-07-14 23:17 UTC, LanceSmites328 requested changes

2023-07-14 23:17 UTC, LanceSmites328 commented on code/modules/mob/living/simple_animal/abnormality/he/golden_false_apple.dm
> +	H.adjustSanityLoss(stacks * -0.5)
Now gets added to abnormalities and other hostile creatures, assuming human is no longer reasonable.

2023-07-14 23:17 UTC, LanceSmites328 commented on code/modules/mob/living/simple_animal/abnormality/he/golden_false_apple.dm
> +	H.adjustBruteLoss(stacks * -0.5)
This amount of healing is very unimpactful enemy support.

2023-07-15 00:19 UTC, LanceSmites328 requested changes

2023-07-15 00:19 UTC, LanceSmites328 commented on code/modules/mob/living/simple_animal/abnormality/he/golden_false_apple.dm
> +	if(istype(owner, /mob/living/simple_animal))
```suggestion
	if(isanimal(owner))
```

2023-07-16 16:08 UTC, LanceSmites328 approved these changes

2023-07-16 16:08 UTC, merged