medical vender additions
vlggms/lobotomy-corp13 pull request #1145
Opened 2023-07-15 06:45 UTC by Trilbyspaceclone

## About The Pull Request

Gives medical venders 6 metal injects, 6 sal acid injects 2 boxes of body bags, 1 box of latex gloves and face masks
Adds 12 penlights to the medical vender as well
In its expensive menu you can buy a defib 
Allows 1 defib mount (the ones you place your self) and one self charging defib mount again at high prices

## Why It's Good For The Game

The boxes of body bags go fast if you use them with the intent of burning the body in the bag or to put in a morgue (in some maps)
Gloves and masks are QoL for people that late join or respawn after dusting a few times
Extra injectors give a bit more use for personal money

Penlights are amazing.

Defib is a investment allowing someone to in a short window revive the non-dusted or gibbed folks, making not only the surgery table more viable but also allows folks hope that even if they die they can be revived rather then instantly respawning.

If defibs are a hard no I understand and will remove it from the PR

## Changelog
:cl:
add: Added new things to the medical vender, boxes of body bags, gloves, masks, hypo sprays, penlights ect
add: A pare of defibs can be obtained via the medical vender for a high price
/:cl:

2023-07-15 06:59 UTC, Trilbyspaceclone commented
Thats a sad!
I wounder if revival surgery is on the table or not tho

2023-07-15 07:05 UTC, Trilbyspaceclone commented
> No revival surgery for the same reason. Death should be final, and revival methods mean any abnorm that can't gib is completely invalidated.

Understood, and completely reasonable! I just wish their was more time to save people V_V

2023-07-15 09:49 UTC, Kitsunemitsu requested changes
Remove the gloves, you get those from Cargo

2023-07-15 10:50 UTC, Trilbyspaceclone commented on code/modules/vending/medical.dm
> +					/obj/item/storage/box/gloves = 1,
```suggestion
```

2023-07-17 00:43 UTC, Kitsunemitsu approved these changes
Approved/

2023-07-17 00:43 UTC, merged