Burrowing Heaven
vlggms/lobotomy-corp13 pull request #1160
Opened 2023-07-21 08:16 UTC by Kitsunemitsu

## About The Pull Request
Adds the burrowing heaven, with a few minor changes.

1) It moves around. This lets you corner it in certain places, or catch it just as it's about to hit a body.
2) Requires 2 people to look at it, opposite of Schadenfreude.

## Why It's Good For The Game

## Changelog
:cl:
add: Added Burrowing HEaven
/:cl:

2023-08-12 07:06 UTC, Kitsunemitsu commented on code/modules/mob/living/simple_animal/abnormality/waw/burrowing_heaven.dm
> +		SLEEP_CHECK_DEATH(5 SECONDS)
Haven't tried that, will do.

2023-10-28 18:58 UTC, LanceSmites328 commented on code/modules/clothing/suits/ego_gear/waw.dm
> +	armor = list(RED_DAMAGE = 30, WHITE_DAMAGE = 40, BLACK_DAMAGE = 40, PALE_DAMAGE = 30) // 140
holy shit WAW magic bullet

2023-10-28 19:01 UTC, LanceSmites328 requested changes

2023-10-28 19:01 UTC, LanceSmites328 commented on code/modules/paperwork/records/info/waw.dm
> +		"The burrowing Heaven became completely stationary when it was viewed by two or more people. Please take this into account when suppressing it.")
```suggestion
		"The Burrowing Heaven became completely stationary when it was viewed by two or more people. Please take this into account when suppressing it.")
```

2023-10-28 19:02 UTC, LanceSmites328 commented
Doesn't this just walk around right now and hit people instead of teleporting and doing room based damage?

2024-01-31 16:11 UTC, Kitsunemitsu commented on code/modules/mob/living/simple_animal/abnormality/waw/burrowing_heaven.dm
> +/mob/living/simple_animal/hostile/abnormality/burrowingheaven/Life()
For Schad it's used for movement, was also used for movement on BH too.

2025-08-11 23:55 UTC, closed without merging