Ordeal Despawns
vlggms/lobotomy-corp13 pull request #117
Opened 2022-08-07 06:21 UTC by PotatoTomahto

## About The Pull Request
[BETACORP CHANGES REVERTED SINCE DERP'S IS BETTER] Lore papers have been fixed. Amber dawn, green dawn, and green noons spawned from dusks now disappear upon death. Greens are now butcherable.

## Why It's Good For The Game
Derp's map changes are better. Janitor clerks and abnorm coders can now rejoice as dusk ordeals no longer clutter entire hallways with bodies.

## Changelog
:cl:
add: green butchering and certain ordeal despawns
add: gives clerk hunting knives (nerfed damage)
tweak: boxes have now explorer masks since they look cooler
fix: lore papers
:cl:

2022-08-07 07:04 UTC, Kitsunemitsu commented
Don't make them despawn, make them butcher.
Give all clerks a butchering knife

2022-08-07 07:13 UTC, Kitsunemitsu commented
I want to say that this is made as a stealth nerf in bad faith.
![image](https://user-images.githubusercontent.com/77302679/183279575-221e96f3-f263-4532-8029-7e1a28de353d.png)

This Coder knows that this is a stealth nerf to certain abnormalities and ordeals.

I suggested to just make it a subtype of the Robots that disappear.
Have the factory spawn the subtype and dawn and noon stay.

Rest can stay.

2022-08-07 10:46 UTC, EgorDinamit requested changes
Ordeals shouldn't despawn on death, that's what clerks are supposed to be doing.

2022-08-08 21:03 UTC, EgorDinamit commented on code/modules/mob/living/simple_animal/hostile/ordeal/green.dm
> +/mob/living/simple_animal/hostile/ordeal/green_bot/factory
There is absolutely no reasons to add an entire subtype for it.
Just make factory register a signal for death.

2022-08-08 22:42 UTC, merged