Work damage is now consistent
vlggms/lobotomy-corp13 pull request #1217
Opened 2023-08-07 00:24 UTC by Kitsunemitsu

## About The Pull Request
Makes work damage more consistent.
Zayin: 4-6 
Teth: 6-8 
He: 9-11
Waw: 12-15
Aleph: 16-20

## Why It's Good For The Game
Many, Many inconsistencies.
Some Waws did the same work damage as Zayins.
Wellcheers did 1 red.

## Changelog
:cl:
balance: rebalanced all work damage to be consistent
fix: Letters on Standby now actually does work damage
/:cl:

2023-08-07 02:38 UTC, LanceSmites328 reviewed
Needs to be tested heavily as this seemingly small change dramatically affects the speed at which people level and acquire PE. More damage = More time resting = Ordeals arriving with less gear.

2023-08-08 21:57 UTC, Kitsunemitsu commented on code/modules/mob/living/simple_animal/abnormality/aleph/nihil.dm
> +	work_damage_amount = 20
Will change in a bit/

2023-08-10 18:58 UTC, Coxswain-Navigator commented
I wouldn't jump the gun on enforcing this, as abnormalities do NOT have standardized work rates. This is not me telling you to go and standardize work rates, as diversity is the greatest appeals of abnormalities.

2023-08-30 07:45 UTC, LanceSmites328 requested changes

2023-08-30 07:45 UTC, LanceSmites328 commented on code/modules/mob/living/simple_animal/abnormality/waw/hatred_queen.dm
> +	work_damage_amount = 15
The fact that her damage DOUBLES when she goes hysteric (which is a regular occurrence) has NOT been accounted for, causing her do deal **30** black damage per tick. Please consider reducing this to 10-12

2023-08-30 14:07 UTC, Kitsunemitsu commented
> I will say that overall this seems to be an increase in damage which at this point kinda serves to slow the progress of agents down more while not offering _anything_ in exchange. People have also made good points in the thread about how it DOES currently affect workflow and it's not been beneficial for the game at this time. Standardization is great but the overall ramp just isn't it.

This PR is intended to punish players who do not actually wear armor to work on Waw abnormalities.
This slows down the game state a little; _However_ It is also more punishing on experienced players.
New players that could get 3 works in now can get 2 works in.
Experienced players that could get 5 works in now can get 3 works in.

2023-09-29 18:59 UTC, closed without merging