adds missed reaper
vlggms/lobotomy-corp13 pull request #1227
Opened 2023-08-10 00:04 UTC by Coxswain-Navigator

## About The Pull Request
New HE - level abnormality that deals pale damage, with a nasty breach.

## Why It's Good For The Game
Is it?

## Changelog
:cl:
add: Added missed reaper
/:cl:

2023-08-13 06:04 UTC, Coxswain-Navigator commented on code/modules/mob/living/simple_animal/abnormality/he/missed_reaper.dm
> +	addtimer(CALLBACK(src, .proc/explode), 0.5 SECONDS)
Well, the spawning shadow I only want its deletion handled by the explode() proc so there's no reason to change it to a temp visual.
The temporary shadow is a subtype of a permenant version that just expires.
This process doesn't really leave much of a reason to create a new temp visual object that fulfills the same purpose, as it's simpler this way.

2023-08-13 22:03 UTC, LanceSmites328 requested changes

2023-08-13 22:52 UTC, Coxswain-Navigator commented on code/modules/mob/living/simple_animal/abnormality/he/missed_reaper.dm
> +		playsound(get_turf(Y), 'sound/abnormalities/missed_reaper/shadowcast.ogg', 50, FALSE, -1)
very nice!

2023-08-16 17:48 UTC, Coxswain-Navigator commented
Test-merges haven't revealed any further issues with this.

2023-08-16 21:07 UTC, LanceSmites328 approved these changes

2023-08-16 21:08 UTC, merged