Adds Norinori
vlggms/lobotomy-corp13 pull request #1260
Opened 2023-08-21 05:46 UTC by Coxswain-Navigator

## About The Pull Request
New abnormality

## Why It's Good For The Game
Is it?

## Changelog
:cl:
add: Added Norinori, a new abnormality.
/:cl:

2023-08-24 04:16 UTC, TravisAngeI commented
i get the feeling it's gonna look very pettable based off the gimmick it has lol

2023-09-12 01:45 UTC, LanceSmites328 commented on code/modules/mob/living/simple_animal/abnormality/he/norinori.dm
> +						ABNORMALITY_WORK_ATTACHMENT = -80,
He hates you, but not as much as General Bee hates you

2023-09-12 01:55 UTC, LanceSmites328 requested changes

2023-09-12 01:55 UTC, LanceSmites328 commented on code/modules/mob/living/simple_animal/abnormality/he/norinori.dm
> +	to_chat(user, "<span class='userdanger'>[src] mutilates you!</span>")
```suggestion
	user.visible_message("<span class='warning'>[src] mutilates [user]!</span>", "<span class='userdanger'>[src] mutilates you!</span>")
```
Let people know what's happenin

2023-09-12 01:55 UTC, LanceSmites328 commented on code/modules/mob/living/simple_animal/abnormality/he/norinori.dm
> +	user.gib() //update it with cool effects
Hear me out,
```suggestion
	if(user.stat == DEAD)
		user.gib() //update it with cool effects
```
IF someone with max fortitude, KoD blessing, and Mimicry wants to pet the funny cat and get ALMOST Murdered, let them!

2023-09-12 01:55 UTC, LanceSmites328 commented on code/modules/mob/living/simple_animal/abnormality/he/norinori.dm
> +		damage_coeff[damtype] += 0.4
If/When #1326 gets merged, remind me to change this to a dc_change

2023-09-12 01:55 UTC, LanceSmites328 commented on code/modules/paperwork/records/info/he.dm
> +		"When communicating with the abnormality as a part of Attachment Work, the employee was viciously attacked by the abnormality and killed.",
```suggestion
		"When communicating with the abnormality as a part of Attachment Work, the employee was viciously attacked and killed by the abnormality.",
```

2023-09-12 01:55 UTC, LanceSmites328 commented on code/modules/paperwork/records/info/he.dm
> +		"When the work result was Bad, the Qliphoth Counter lowered with a high probability.")
```suggestion
		"When the work result was Bad, the Qliphoth Counter lowered.")
```

2023-09-12 01:55 UTC, LanceSmites328 commented on code/modules/paperwork/records/info/he.dm
Doesn't mention that his qliphoth lowers due to deaths at all.

2023-09-12 01:56 UTC, Coxswain-Navigator commented on code/modules/paperwork/records/info/he.dm
Now that you mention it that's probably just an alpha feature that I forgot to remove later.

2023-09-12 02:27 UTC, LanceSmites328 requested changes

2023-09-12 02:27 UTC, LanceSmites328 commented on code/modules/paperwork/records/info/he.dm
> +		"When communicating with the abnormality as a part of Attachment Work, the employee was viciously attacked by the abnormality and killed by the abnormality.",
That reads even worse than before.
```suggestion
		"When communicating with the abnormality as a part of Attachment Work, the employee was viciously attacked and killed by the abnormality.",
```

2023-09-12 02:28 UTC, Coxswain-Navigator commented on code/modules/paperwork/records/info/he.dm
> +		"When communicating with the abnormality as a part of Attachment Work, the employee was viciously attacked by the abnormality and killed by the abnormality.",
oh... whoops!

2023-09-12 03:56 UTC, LanceSmites328 approved these changes

2023-09-12 03:57 UTC, merged