Ports radio noises
vlggms/lobotomy-corp13 pull request #1261
Opened 2023-08-21 06:00 UTC by Coxswain-Navigator

## About The Pull Request
Ports https://github.com/Quasar-13/Quasar-13/pull/443 on request of our beloved headcoder.

## Why It's Good For The Game
More annoying rounds

## Changelog
:cl:
soundadd: added radio sound effects
/:cl:

2023-08-21 06:02 UTC, Kitsunemitsu submitted a review, later dismissed
Port I 100% know works.

2023-08-22 03:41 UTC, LanceSmites328 approved these changes

2023-08-22 21:22 UTC, EgorDinamit requested changes
- Make it a preference option to hear those sounds.
- Reduce the volume and range of the sound itself, so that people don't get earblasted from 5 tiles away.

2023-08-22 21:23 UTC, EgorDinamit commented on code/game/objects/items/devices/radio/radio.dm
> +		var/sound/radio_sound = pick(radio_sounds)
What you are picking isn't a type of sound datum, just a path.
```suggestion
		var/radio_sound = pick(radio_sounds)
```

2023-08-22 21:24 UTC, EgorDinamit commented on code/game/objects/items/devices/radio/radio.dm
> +	if(radio_sounds.len) //Sephora - Radios make small static sounds now.
This is honestly a nitpick, but:
```suggestion
	if(LAZYLEN(radio_sounds)) //Sephora - Radios make small static sounds now.
```
Never use A.len, instead opt in for length(A) proc.

2023-08-23 15:56 UTC, Coxswain-Navigator commented
> * 
> * Reduce the volume and range of the sound itself, so that people don't get earblasted from 5 tiles away.

I did the latter, but I believe the former would require me to write a new copy of the radio proc or the playsound() proc, which seems like unnecessary bloat. How would this respect radios that are on the floor with no player otherwise?

2023-08-23 16:04 UTC, EgorDinamit commented
What? You just tie preference to sound being sent to the player with it disabled.

2023-08-24 02:24 UTC, LanceSmites328 submitted a review, later dismissed

2023-08-28 09:23 UTC, EgorDinamit approved these changes
Looks more or less fine; If nothing breaks during test-merge - it is good to go.

2023-08-30 07:25 UTC, merged