Rep Console Update
vlggms/lobotomy-corp13 pull request #1271
Opened 2023-08-24 06:22 UTC by Kitsunemitsu

## About The Pull Request
Updates the Rep Console to have some basic sales stuff, and the sales works as intended

## Why It's Good For The Game
More........ MORE!

## Changelog
:cl:
add: Added stuff for reps to sell
/:cl:

2023-08-24 20:45 UTC, LanceSmites328 commented on ModularTegustation/representative_console.dm
> +	research_desc = "Hey, listen buddy, it's Joe from research. <br>The supply team went home for the night, and I'm tired, but I need this tested. <br>It'll revive one guy, once. It's a major breakthro
Joe K-Corp

2023-08-24 20:47 UTC, LanceSmites328 commented on ModularTegustation/representative_console.dm
> +	research_desc = "You can PROBABLY convince HQ Extraction to give you another set of 3 abnos, as you're pretty tight with Big B. "
![128ba089da7f53c7fa19add35be1e012e3fde76007c0d6b904707e51a91010d6_1](https://github.com/vlggms/lobotomy-corp13/assets/61567407/a4f44f2f-c040-435c-a0e4-b5acf84e1297)

2023-08-26 00:50 UTC, LanceSmites328 requested changes

2023-08-26 00:50 UTC, LanceSmites328 commented on ModularTegustation/tegu_items/representative/research.dm
Holds duplicate research to that in representative_console.dm

2023-08-26 00:51 UTC, Kitsunemitsu commented on ModularTegustation/tegu_items/representative/research.dm
Ah, will be removed in a bit

2023-08-30 08:13 UTC, LanceSmites328 reviewed
Let me know when merge conflicts are fixed

2023-09-08 06:50 UTC, LanceSmites328 approved these changes

2023-09-08 06:50 UTC, merged