Various Text Changes
vlggms/lobotomy-corp13 pull request #1320
Opened 2023-09-02 01:52 UTC by PotatoTomahto

## About The Pull Request
Text:
- Records work damage written in all caps
- Queue console outputs have different styles to make them more noticeable
- Quirk descriptions made more consistent
- "Show Attributes" changed to "View Attributes" so its sorted next to "View Gifts"

Makes all telecomms and some LCorp machines indestructible.

## Why It's Good For The Game
Lots of minor text or description changes I wanted. Also stop breaking tcomms.

## Changelog
:cl:
tweak: lots of text, roulette
/:cl:

2023-09-02 22:30 UTC, LanceSmites328 submitted a review, later dismissed

2023-09-02 23:44 UTC, Kitsunemitsu requested changes
Stop fucking with resistance to text. We talked about this before, and Resistant is a more clear name than ineffective.

I really don't like how this removes any sort of obscurity with the armor values, giving people raw values is an invitation to use math. I don't want to encourage people calculating exactly how much damage they'd do with X weapon vs Y weapon, as it feels EXTREMELY gamey.

2023-09-02 23:44 UTC, Kitsunemitsu requested changes
Atomize PR.

2023-09-02 23:50 UTC, Kitsunemitsu requested changes
Don't put text changes and a fix PR into one.
If you REALLY want to put up the resistance to text PR, make it it's own PR, I however, will likely not merge a needless change such as this, to overhaul a system to use more vague wording, and encouraging the players to use math.

The Text changes and roulette should honestly two separate PRs.

2023-09-02 23:50 UTC, Kitsunemitsu commented on code/__HELPERS/abnormalities.dm
>  		if(0 to 0) //Just putting 0 doesn't work.
This is not how switches work. It was fine before.

2023-09-02 23:50 UTC, Kitsunemitsu commented on code/game/machinery/computer/abnormality_queue.dm
> +		to_chat(usr, "<span class='boldnotice'>A random Abnormality has been selected. LobCorp HQ has reimbursed you for the costs of extracting a specific Abnormality.</span>")
Don't use LobCorp, in lore it's L Corp

2023-09-02 23:50 UTC, Kitsunemitsu commented on code/game/machinery/roulette_machine.dm
> +/obj/machinery/roulette/Destroy()
Why is any of this in this PR?

2023-09-04 04:53 UTC, LanceSmites328 approved these changes

2023-09-04 05:30 UTC, Kitsunemitsu approved these changes
Looks good to me.

2023-09-04 05:30 UTC, merged