adds poor screenwriter's note
vlggms/lobotomy-corp13 pull request #1321
Opened 2023-09-02 05:32 UTC by Coxswain-Navigator

## About The Pull Request
Adds poor screenwriter's note

## Why It's Good For The Game
Is it?

## Changelog
:cl:
add: Added poor screenwriter's note
/:cl:

2023-09-16 15:36 UTC, TravisAngeI commented
Minor misspell on the 'A' simplemob's examine I think, it says 'screepy' when I think it should be 'creepy'

2023-09-17 03:14 UTC, LanceSmites328 commented on code/modules/mob/living/simple_animal/abnormality/waw/screenwriter.dm
> +	SSlobotomy_corp.work_logs += "\[[worldtime2text()]\] [name]: [user_job_title] [user.real_name] (LV [user.get_text_level()]): Performed [work_type], [pe]/[max_boxes] PE."
Note to self, find a way to make this unncessary

2023-09-17 03:18 UTC, LanceSmites328 requested changes

2023-09-17 03:18 UTC, LanceSmites328 commented on code/modules/mob/living/simple_animal/abnormality/waw/screenwriter.dm
> +				if(H.ai_controller == /datum/ai_controller/insane/suicide/scene)
Shouldn't this be a type check?

2023-09-17 03:18 UTC, LanceSmites328 commented on code/modules/mob/living/simple_animal/abnormality/waw/screenwriter.dm
> +	..()
```suggestion
	. = ..()
```

2023-09-21 01:39 UTC, LanceSmites328 requested changes
Changes suggested are based on #1420

2023-09-21 01:39 UTC, LanceSmites328 commented on code/modules/mob/living/simple_animal/abnormality/waw/screenwriter.dm
> +	preferred_work_type = pick(work_types)
Can't you do `pick(work_chances)`?

2023-09-21 01:39 UTC, LanceSmites328 commented on code/modules/mob/living/simple_animal/abnormality/waw/screenwriter.dm
> +	)
```suggestion
	)
	work_attribute_types = list(
		"Nutrition" = FORTITUDE_ATTRIBUTE,
		"Cleanliness" = PRUDENCE_ATTRIBUTE,
		"Consensus" = PRUDENCE_ATTRIBUTE,
		"Amusement" = TEMPERANCE_ATTRIBUTE,
		"Violence" = JUSTICE_ATTRIBUTE
	)
		
```
May need to rebase for this to work.

2023-09-21 01:39 UTC, LanceSmites328 commented on code/modules/mob/living/simple_animal/abnormality/waw/screenwriter.dm
> +	SSlobotomy_corp.work_logs += "\[[worldtime2text()]\] [name]: [user_job_title] [user.real_name] (LV [user.get_text_level()]): Performed [work_type], [pe]/[max_boxes] PE."
```suggestion
	preferred_work_type = pick(work_types)
	SpawnIcon()
```

2023-09-21 21:24 UTC, LanceSmites328 approved these changes

2023-09-21 21:24 UTC, merged