Add realized armor for yin and yang plus rebalanced a lot of other realized armors
vlggms/lobotomy-corp13 pull request #1361
Opened 2023-09-06 13:52 UTC by CrabbytheCrab

## About The Pull Request

Adds realized armors both both yin and yang called harmony of duality and duality of harmony respectively.

Harmony of duality has 0.1/0.6/0.1/0.6(or  9/4/9/4) and has an ability called Anarchy. Anarchy is a targetable realized ability with a minute cooldown that lets you fire a laser dealing 1000 black damage(probably way too much) and if you hit another player(or yourself) with it they'll gain a + 20 justice buff for a minute and a half. If someone gets hir by Anarchy and is wearing Duality of harmony they'll get a buff that decreases red and pale black taken by 25% and increases their stats by 10 for 90 seconds.

Duality of harmony has 0.4/0/0.4/0.8(or IV/X/IV/VIII and has an ability called Tranquility. Tranquility is a charge up ability with a minute cool down that lets you explode like how yang does on death dealing 400 white damage and healing people caught in its blast for 120 hp and sp. If someone gets healed by Tranquility and is wearing Harmony of duality they'll get a buff that decreases white and pale damage taken by 25% and increases their stats by 10 for 90 seconds.

Duality of harmony and Harmony of duality sound broken as fuck(they probably need to be toned down) but here's a catch, you need to have both yin and yang to be able to realize them and having both yin and yang are quite risky already.

For the balancing changes for some other realized abilities:

Buffed quenched with blood's ability from 2 swords to 3 swords with a damage cap of 150(and added the sword sounds kod makes)

Make fallen color's ability's damage higher(200 black with 40 fall off per tile) making it more of the chaotic cluster fuck it was meant to be

Buff mouth of god's abilities heavily. the counter time is increased from 2 seconds to 5 seconds, area of the counter is bigger, and increased the justice buff's duration to 20 seconds from 15

Buff sakura bloom's ability cooldown back to how it was(30 seconds)

Buff eye's of god's slow down from a 50% slow to a 80% slow

Nerfed death stare's ability heath to 250 and attack speed to every 3 seconds(slowdown buffed to 3 seconds to compinsate)

## Why It's Good For The Game

Adding realized armors for both yin and yang that requires having both makes having the 2 more worthwhile and makes the dragon of harmony show up more often

quenched with blood's ability sucked since at most it was 80 pale damage to one target(40 pale to two) while head of god's ability did 150 pale to an area and makes them take 50% more pale with the same cooldown. making  quenched with blood's ability be 3 swords with a 150 damage cap helps it be a more single target version of head of god's ability.

Fallen color's ability was meant to be more destructive so buffing the max amount of damage it could do will help it being high risk high reward. Also fixed it's passive ability being able to go off during work damage.

Mouth of god's ability kind of sucked to use so giving it a bigger window, buffing its range, and making the justice buff last longer will help it be more useful and increases the reward.

Sakura bloom's was too strong before since it had a constant rate of healing instead of burst healing so I felt that it could have its old cooldown of 30 seconds back since the burst healing is a lot less useful.

Eye's of god was always meant to have a 80% slow, this change fixes that.

Death's stare's ability was broken before, not sure if a 16% health nerf and a 50% decreased attack speed will make it balanced or if it will be op.
## Changelog
:cl:
add: duality of harmony, harmony of duality, and their abilities and buffs
tweak: makes fallen color's passive not go off during work
balance: buffed the abilities of  quenched with blood, fallen colors, sakura bloom, mouth of god, and eyes of god, and nerfed  the ability of death's stare
fix: fixed a few things
soundadd: gave  quenched with blood's ability sound
imageadd: added some icons and images
code: adds a check for the realizer for having both yin and yang
/:cl:

2023-09-06 19:55 UTC, Coxswain-Navigator commented on code/modules/spells/ability_types/realized.dm
> +	desc = "Decrese white and pale damage taken by 25%. \
typo

2023-09-06 19:56 UTC, Coxswain-Navigator commented on code/modules/spells/ability_types/realized_aimed.dm
> +	var/damage = 1000  // Amount of black damage dealt to enemies from the laser.
You don't think 1000 damage in an AOE on a 60 second cooldown is too much?

2023-09-07 22:53 UTC, Kitsunemitsu commented
Don't notate in decimals.
Notation on PRs should be #/#/#/#
Such as 5/6/6/5 or 6/6/6/6

2023-09-07 22:53 UTC, Kitsunemitsu commented
Also what's the point of all these buffs........

2023-09-07 23:13 UTC, CrabbytheCrab commented
> Also what's the point of all these buffs........
> 
> Applying DNM until author can explain the reason of their buffs and nerfs, seemingly at random

2023-09-07 23:15 UTC, CrabbytheCrab commented
those balancing changes were due to me asking about which of the realized armors a pr made before needed to be buffed or nerfed and quenched with blood was brought up during one. im willing to undo sakura bloom's, eyes of god, and fallen colors changes since those we're by decision fully

2023-09-07 23:52 UTC, CrabbytheCrab commented
did the split

2023-09-12 01:10 UTC, Kitsunemitsu commented
Balancing changes removed.

2023-09-12 01:43 UTC, LanceSmites328 requested changes

2023-09-12 01:43 UTC, LanceSmites328 commented on code/modules/clothing/suits/ego_gear/realized.dm
> +	desc = "When good an evil meet discord and assonance will be quelled."
```suggestion
	desc = "When good and evil meet discord and assonance will be quelled."
```

2023-09-12 01:43 UTC, LanceSmites328 commented on code/modules/mob/living/simple_animal/abnormality/_tools/zayin/realizer.dm
> +	if(I.type == yang_armor && !YinYangCheck() || I.type == yin_armor && !YinYangCheck())
```suggestion
	if((istype(I, /obj/item/clothing/suit/armor/ego_gear/waw/discord) || istype(I, /obj/item/clothing/suit/armor/ego_gear/waw/assonance) && !YinYangCheck())
```

2023-09-12 01:43 UTC, LanceSmites328 commented on code/modules/mob/living/simple_animal/abnormality/_tools/zayin/realizer.dm
> +	var yin_armor = /obj/item/clothing/suit/armor/ego_gear/waw/discord
```suggestion
```

2023-09-12 01:43 UTC, LanceSmites328 commented on code/modules/spells/ability_types/realized.dm
> +/obj/effect/proc_holder/ability/tranquility/Perform(target, mob/user)
```suggestion
/obj/effect/proc_holder/ability/tranquility/Perform(target, mob/living/carbon/human/user)
```

2023-09-12 01:43 UTC, LanceSmites328 commented on code/modules/spells/ability_types/realized.dm
> +			all_turfs -= T
```suggestion
	for(var/i = 0 to explosion_range)
		for(var/turf/T in all_turfs)
			if(get_dist(user, T) > i)
				continue
			new /obj/effect/temp_visual/dir_setting/speedbike_trail(T)
			user.HurtInTurf(damage_amount, list(), WHITE_DAMAGE)
			for(var/mob/living/carbon/human/L in T)
				if(!user.faction_check_mob(L, FALSE))
					continue
				if(L.stat == DEAD)
					continue
				if(L.is_working) //no work heal :(
					continue
				L.adjustBruteLoss(-120)
				L.adjustSanityLoss(-120)
				if(istype(L.get_item_by_slot(ITEM_SLOT_OCLOTHING), /obj/item/clothing/suit/armor/ego_gear/realization/duality_yin))
					H.apply_status_effect(/datum/status_effect/duality_yang)
					new /obj/effect/temp_visual/healing(get_turf(L))
			all_turfs -= T
```
I will also note that the healing VFX only applies to those who have the opposing suit on at the moment.

2023-09-12 01:43 UTC, LanceSmites328 commented on code/modules/spells/ability_types/realized_aimed.dm
> +				continue
```suggestion
```
None of these checks are particularly relevant to any scenario that this buff would be disruptive to.

2023-09-12 01:43 UTC, LanceSmites328 commented on code/modules/spells/ability_types/realized_aimed.dm
> +			if(istype(Z))
```suggestion
			if(istype(L.get_item_by_slot(ITEM_SLOT_OCLOTHING), /obj/item/clothing/suit/armor/ego_gear/realization/duality_yang))
```

2023-09-12 01:43 UTC, LanceSmites328 commented on code/modules/spells/ability_types/realized_aimed.dm
> +	var/list/spawned_effects = list()
```suggestion
```
You don't do anything with this list, nothing's added to it.

2023-09-12 01:43 UTC, LanceSmites328 commented on code/modules/spells/ability_types/realized_aimed.dm
> +		qdel(FX)
```suggestion
```

2023-09-12 01:43 UTC, LanceSmites328 commented on code/modules/spells/ability_types/realized_aimed.dm
> +	var/turf/my_turf = get_turf(H)
```suggestion
/obj/effect/proc_holder/ability/aimed/yin_laser/proc/Cast(turf/target, mob/living/carbon/human/user)
	user.face_atom(target)
	var/turf/my_turf = get_turf(user)
```

2023-09-12 02:05 UTC, LanceSmites328 approved these changes
If the numbers on these pieces of EGO are a problem in the future, we can change them. They are currently implemented as is as managing both Yin and Yang is risky as hell and both getting out can spell disaster for a facility.

2023-09-12 02:08 UTC, merged