Speed code unification
vlggms/lobotomy-corp13 pull request #1408
Opened 2023-09-15 05:23 UTC by InsightfulParasite

## About The Pull Request
changed the move_to_delay defines with a speed change proc.
I have to test 

- [ ] Melting Love
- [ ] Mountain of Smiling Bodies
- [ ] Titania
- [ ] Blue Shepherd
- [ ] Golden False Apple
- [ ] Red Buddy
- [ ] You Strong
- [ ] Void Dream
- [ ] Nosferatu
- [ ] Warden
- [ ] Indigo Midnight Matriarch

## Why It's Good For The Game
Slowdown bullets wont make them go extremely fast anymore.

## Changelog
:cl:
fix: Speed Define super speed bug
/:cl:

2023-09-17 22:00 UTC, LanceSmites328 requested changes

2023-09-17 23:20 UTC, InsightfulParasite commented on code/modules/mob/living/simple_animal/abnormality/he/golden_false_apple.dm
> -		for(var/mob/living/L in HurtInTurf(T, list(), 200, RED_DAMAGE, check_faction = TRUE, hurt_mechs = TRUE))
Because it doesnt return a list. It harms the things surrounding it but the things are not collected.

2023-09-17 23:21 UTC, InsightfulParasite commented on code/modules/mob/living/simple_animal/abnormality/he/golden_false_apple.dm
Yeah you know what i may just ignore false apple and seperate that into another PR.

2023-09-17 23:21 UTC, InsightfulParasite commented on code/modules/mob/living/simple_animal/abnormality/he/you_strong.dm
> +	SpeedChange(-1 * FLOOR(gear / 3, 1))
I dont know if thats true because for some reason the revive proc resets move_to_delay. Lemme check.

2023-09-17 23:23 UTC, InsightfulParasite commented on code/modules/mob/living/simple_animal/abnormality/he/golden_false_apple.dm
Dont get me wrong though golden apple was genuinely broken and not working. The beazerk function didnt work and caused runtimes.

2023-09-17 23:33 UTC, InsightfulParasite commented on code/modules/mob/living/simple_animal/abnormality/he/golden_false_apple.dm
> -		for(var/mob/living/L in HurtInTurf(T, list(), 200, RED_DAMAGE, check_faction = TRUE, hurt_mechs = TRUE))
Also i dont know why it would work in the first place because it doesnt return a list of things.

2023-09-17 23:35 UTC, LanceSmites328 commented on code/modules/mob/living/simple_animal/abnormality/he/golden_false_apple.dm
> -		for(var/mob/living/L in HurtInTurf(T, list(), 200, RED_DAMAGE, check_faction = TRUE, hurt_mechs = TRUE))
> Because it doesnt return a list. It harms the things surrounding it but the things are not collected.

Yes it does, read the proc again.

2023-09-17 23:37 UTC, InsightfulParasite commented on code/modules/mob/living/simple_animal/abnormality/he/golden_false_apple.dm
> -		for(var/mob/living/L in HurtInTurf(T, list(), 200, RED_DAMAGE, check_faction = TRUE, hurt_mechs = TRUE))
Wait maybe i misread something

2023-09-18 00:04 UTC, InsightfulParasite commented on code/modules/mob/living/simple_animal/abnormality/he/you_strong.dm
> +	SpeedChange(-1 * FLOOR(gear / 3, 1))
No your right the speed is stacking. I think i fixed it now.

2023-09-18 02:02 UTC, InsightfulParasite commented on code/modules/mob/living/simple_animal/abnormality/he/golden_false_apple.dm
> -		for(var/mob/living/L in HurtInTurf(T, list(), 200, RED_DAMAGE, check_faction = TRUE, hurt_mechs = TRUE))
Yeah im wrong it does return a list.

2023-09-23 00:02 UTC, LanceSmites328 approved these changes

2023-09-24 03:03 UTC, merged