Revert "Fix training core debuffs & buffs"
vlggms/lobotomy-corp13 pull request #1428
Opened 2023-09-19 13:47 UTC by Kitsunemitsu

Reverts vlggms/lobotomy-corp13#1409

This PR makes it quite literally impossible to hit statcheck abnos after noon.
IE: Warden.

Overall, the game is significantly harder than intended.
Lowering your actual stats is better than being unable to hit certain statchecks

2023-09-19 18:07 UTC, EgorDinamit requested changes
We're not turning Training core into a joke.
It shall remain what it originally was, and always was meant to be.

2023-09-20 10:55 UTC, Kitsunemitsu commented
My brother in christ some abnormalities literally cannot be worked on.

2023-09-23 19:18 UTC, Kitsunemitsu commented
Copy that, will fix.

2023-09-30 16:52 UTC, Kitsunemitsu commented
Closing and reopening

2023-09-30 16:52 UTC, closed without merging