Reworks some TETH abnormalities
vlggms/lobotomy-corp13 pull request #1522
Opened 2023-10-13 20:50 UTC by Coxswain-Navigator

## About The Pull Request
Improves some abnormalities that I feel are a bit incomplete

## Why It's Good For The Game
Less boring stuff

## Changelog
:cl:
tweak: tweaked some TETH abnormalities
/:cl:

2023-10-17 04:13 UTC, LanceSmites328 requested changes

2023-10-17 04:13 UTC, LanceSmites328 commented on code/modules/mob/living/simple_animal/abnormality/teth/fairy_gentleman.dm
> +			return
```suggestion
```

2023-10-20 08:32 UTC, EgorDinamit commented on code/modules/mob/living/simple_animal/abnormality/teth/fairy_gentleman.dm
> +	attack_action_types = list(/datum/action/innate/abnormality_attack/toggle/FairyJump_Toggle)
Against the naming conventions.

2023-10-28 18:32 UTC, LanceSmites328 requested changes

2023-10-28 18:32 UTC, LanceSmites328 commented on code/modules/mob/living/simple_animal/abnormality/teth/fairy_gentleman.dm
> +		return ..()
```suggestion
```

2023-10-28 18:32 UTC, LanceSmites328 commented on code/modules/mob/living/simple_animal/abnormality/teth/so_that_no_cry.dm
> +	damage_coeff = list(BRUTE = 1, RED_DAMAGE = 1.5, WHITE_DAMAGE = 1, BLACK_DAMAGE = 1, PALE_DAMAGE = 2)
This needs to be updated to reflect #1326 . In this case it'd be
```suggestion
	damage_coeff.ChangeResistances(list(RED_DAMAGE = 0, WHITE_DAMAGE = 0, BLACK_DAMAGE = 0, PALE_DAMAGE = 0))
	SLEEP_CHECK_DEATH(10 SECONDS)
	icon_state = icon_living
	damage_coeff.ChangeResistances(list(RED_DAMAGE = 1.5, WHITE_DAMAGE = 1, BLACK_DAMAGE = 1, PALE_DAMAGE = 2))
```
This *may* need to be rebased for this to properly apply.

2023-10-31 01:12 UTC, LanceSmites328 commented on code/modules/mob/living/simple_animal/abnormality/teth/so_that_no_cry.dm
> +	ChangeResistances(list(BRUTE = 1, RED_DAMAGE = 1.5, WHITE_DAMAGE = 1, BLACK_DAMAGE = 1, PALE_DAMAGE = 2))
Heads up, the Brute change here and in the previous one is redundant, as this proc only changes the provided resistances. Not a real issue but I should let you know.

2023-10-31 01:14 UTC, LanceSmites328 approved these changes

2023-10-31 01:14 UTC, merged