Updates FAN
vlggms/lobotomy-corp13 pull request #1530
Opened 2023-10-15 04:20 UTC by Coxswain-Navigator

## About The Pull Request
Gives FAN a breach and lets it be worked on a meltdown.

## Why It's Good For The Game
Makes FAN less weird.

## Changelog
:cl:
tweak: FAN changed slightly
/:cl:

2023-10-17 04:31 UTC, LanceSmites328 submitted a review, later dismissed

2023-10-19 07:15 UTC, EgorDinamit requested changes
1. Re-using sounds of other abnormalities/objects is bad.
2. You can easily instead of changing description just add it to the examination proc.
3. Do NOT use burn damage. Anything outside of brute damage is pending removal.
4. Not a request, but there are some fancy heat wave effects on Tegu you could try porting.

2023-10-19 07:16 UTC, EgorDinamit commented on code/modules/mob/living/simple_animal/abnormality/he/fan.dm
> +	var/safework //Safe if the abnormality was melting
If it's meant to be a boolean - set its default value to FALSE or TRUE.

2023-10-19 07:17 UTC, EgorDinamit commented on code/modules/mob/living/simple_animal/abnormality/he/fan.dm
> +		sound_to_playing_players_on_level('sound/abnormalities/seasons/summer_idle.ogg', 150, zlevel = z)
That's the only place the proc's argument is used. Can't you just move it to the place where you call HeatWave for the first time?

2023-10-19 07:18 UTC, EgorDinamit commented on code/modules/mob/living/simple_animal/abnormality/he/fan.dm
> +		to_chat(owner, "<span class='warning'>IT'S TOO HOT!</span>")
This will spam itself every 3 seconds. Reconsider.

2023-10-19 07:20 UTC, EgorDinamit reviewed
Another thing worth mentioning - absolutely disgusting implementation of the lists for the "special effect".
As it is right now - there is 3 lists of **references** to mobs. They never get cleaned up. This will chug the server with the BYOND's garbage collector.

2023-10-26 18:50 UTC, EgorDinamit commented on code/modules/mob/living/simple_animal/abnormality/he/fan.dm
> +		if(z != L.z || L.stat >= HARD_CRIT) // on a different Z level or dead
Why check for this? We want to remove it from everyone who was affected.

2023-10-26 18:50 UTC, EgorDinamit commented on code/modules/mob/living/simple_animal/abnormality/he/fan.dm
> +/mob/living/simple_animal/hostile/abnormality/fan/proc/TurnOn(mob/living/carbon/human/user)
Add a sound to it.

2023-10-26 18:51 UTC, EgorDinamit commented on code/modules/mob/living/simple_animal/abnormality/he/fan.dm
> +			V.Destroy()
Do NOT call destroy directly. Always use qdel()

2023-10-26 19:30 UTC, EgorDinamit approved these changes

2023-10-26 20:00 UTC, merged