EGO additions
vlggms/lobotomy-corp13 pull request #1546
Opened 2023-10-17 06:56 UTC by Kitsunemitsu

## About The Pull Request
Adds in Missing EGO from the Abno dump

## Changelog
:cl:
add: Added Visions and U-Turn EGO
/:cl:

2023-11-16 07:40 UTC, Coxswain-Navigator requested changes
Fix these up and I'll approve.

2023-11-16 07:40 UTC, Coxswain-Navigator commented on code/game/objects/items/ego_weapons/he.dm
> +			L.apply_damage(aoe, RED_DAMAGE, null, L.run_armor_check(null, BLACK_DAMAGE), spread_damage = TRUE)
Is this meant to check BLACK armor?

2023-11-16 07:40 UTC, Coxswain-Navigator commented on code/game/objects/items/ego_weapons/teth.dm
> +/obj/item/ego_weapon/lance/visions
This is cool, although I am concerned that it might be a bit feature creeped for a beginner weapon.

2023-12-14 13:17 UTC, Kitsunemitsu commented
No interest in this PR, to be honest.

2023-12-27 22:58 UTC, closed without merging