Turns lantern into teth tier lamp
vlggms/lobotomy-corp13 pull request #1569
Opened 2023-10-22 04:01 UTC by CrabbytheCrab

## About The Pull Request

Makes lantern into a 14 black damage 1.3 attack speed weapon that does aoe.

## Why It's Good For The Game

It's traps was a neat idea but just sucked ass. making it a lamp but teth also sort of makes sense since in lc it did small aoe damage. It being a weaker lamp would let it shine during amber dawn and green noon and a smaller niche for amber dusk.

## Changelog
:cl:
del: Removed lantern traps
balance: rebalanced lantern to lamp lite
/:cl:

2023-10-22 05:03 UTC, LanceSmites328 requested changes
Leave Teth Hammer to something else, this just straight up removes the gimmick of this weapon and makes it fairly generic.

2023-11-01 22:16 UTC, LanceSmites328 requested changes

2023-11-01 22:16 UTC, LanceSmites328 commented on code/game/objects/items/ego_weapons/teth.dm
> +		trap.damage_multiplier = 1 * justicemod
```suggestion
		var/obj/effect/temp_visual/lanterntrap/trap = new(T, user, src, mode)
		trap.damage_multiplier = 1 + get_modified_attribute_level(user, JUSTICE_ATTRIBUTE)/100
```

2023-11-01 22:16 UTC, LanceSmites328 commented on code/game/objects/items/ego_weapons/teth.dm
> +	hitsound = 'sound/weapons/fixer/generic/spear2.ogg'
```suggestion
	hitsound = 'sound/weapons/fixer/generic/spear2.ogg'

```

2023-11-01 22:16 UTC, LanceSmites328 commented on code/game/objects/items/ego_weapons/teth.dm
If you want this to explode on adjacent instead of just when something moves exactly on top of it, try giving it a proximity monitor on Initialize in the auto-mode if-statement, `proximity_monitor = new(src, 1)` (1 radius proximity monitor), and adding the `burst()` proc to `HasProximity`. This would replace the RegisterSignal line.

2024-05-31 16:31 UTC, Kitsunemitsu commented
Lantern was fixed, and we don't really want to touch what is essentially a unique trapper weapon.
It's not used because Meat Lantern sucks and is way too hard for what you get out of it.

Please work on the disease and not the symptoms.

2024-05-31 16:31 UTC, closed without merging

2024-05-31 16:42 UTC, CrabbytheCrab commented
also why talk here when this is old as hell and was before I made the mines better?