Elevator hell
vlggms/lobotomy-corp13 pull request #1575
Opened 2023-10-25 23:28 UTC by CrabbytheCrab

## About The Pull Request

FUCK YOU KIRIE! IF YOU'RE DUMB ENOUGH TO PLAY A MAP THIS WEEKEND, YOU'RE A DUMB ENOUGH SHMUTZ TO LUCAS’ ELEVATOR HELL! BAD DESIGN, ELEVATORS THAT BREAK DOWN, BEES! IF YOU THINK YOUR GOING TO FIND A GOOD ROUND AT ELEVATOR HELL, YOU CAN KISS MY ASS! IT'S OUR BELIEF THAT YOU'RE SUCH A STUPID MOTHERFUCKER THAT YOU'LL FALL FOR THIS BULLSHIT. GUARANTEED! IF YOU FIND A BETTER MAP, YOU CAN SHOVE IT UP YOUR UGLY ASS. YOU HEARD ME RIGHT, SHOVE IT UP YOUR UGLY ASS! BRING YOUR AGENTS, BRING YOUR CLERKS, BRING YOUR AI ASSISTANT, I'LL FUCK HER! THAT'S RIGHT I'LL FUCK YOUR AI ASSISTANT! BECAUSE AT ELEVATOR HELL, YOU'RE FUCKED SIX WAYS TO SUNDAY! TAKE A HIKE TO ELEVATOR HELL! HOME OF CHALLENGE [CENSORED], THAT'S RIGHT, CHALLENGE [CENSORED]. HOW DOES IT WORK? IF YOU CAN [CENSORED] 6 FEET IN THE AIR STRAIGHT AND NOT GET [CENSORED], YOU GET NO WAIT TIMES. DON'T WAIT, DON'T DELAY, DON'T FUCK WITH ME OR I'LL RIP YOUR NUTS OFF! ONLY AT ELEVATOR HELL, THE ONLY MAP THAT TELLS YOU TO FUCK OFF. HURRY UP, ASSHOLE! THIS EVENT ENDS THE MINUTE YOU WRITE ME A REVIEW AND IT BETTER NOT BOUNCE OR YOU'RE A DEAD MOTHERFUCKER. GO TO HELL. ELEVATOR HELL, LC13’S FILTHIEST AND EXCLUSIVE MAP OF THE MEANEST SON OF BITCHES IN THE GAME SS13, GUARANTEED!!

Elevator hell is a map that uses elevators to have 3 wacky floors.

## Why It's Good For The Game

to make people that have ptsd of e corp shit themselves but also be a good map from the pop needed for b corp to d corp that uses elevators.
## Changelog
:cl:
add: Added a new wacky map
imageadd: replaced the gray and black mixed tiles with sprites reflecting the whole versions
code: added elevator 2
/:cl:

2023-10-26 00:10 UTC, Gboster-0 commented
decent copy-pasta, map looks fine

2023-10-26 05:04 UTC, Kitsunemitsu commented on _maps/data/logs/2023/10/24/round-11.55.28/perf-NULL-Meta Station.csv
Why is this here?

2023-10-26 05:04 UTC, Kitsunemitsu commented on _maps/elevator_hell.json
> +	"map_name": "Facility E2-098 Elevator Hell",
Don't call it E2.

2023-10-26 05:04 UTC, Kitsunemitsu requested changes
I'll go over mapping issues on a thread on the discord.

2023-10-30 19:19 UTC, CrabbytheCrab commented
waiting for a new review of this

2023-11-01 01:23 UTC, Retrino commented
reviewed in the thread

2023-11-10 00:09 UTC, CrabbytheCrab commented
how to compact

2023-11-26 03:51 UTC, CrabbytheCrab commented
should I just close this at somepoint?

2024-04-16 00:40 UTC, Kitsunemitsu commented
I thought about it, and I'm not super interested in a new map at this moment. 
Apologies. 

You can talk with skits about it on the discord, and if they approve I'll reopen.

2024-04-16 00:40 UTC, closed without merging