Adds gasharpoon
vlggms/lobotomy-corp13 pull request #1680
Opened 2023-12-02 11:28 UTC by vampirebat74

what it says on the tin

## About The Pull Request

Adds a new "secret" realization engine reward and an interesting weapon option.

TODO: actually create the weapon

## Why It's Good For The Game

New coders might look at this and actually have decent ideas of what a realized suit should actually do

## Changelog
:cl:
add: Adds gasharpoon and pallid tuna
soundadd: added a new sound thingy
imageadd: added relevant icons for gasharpoon
code: TODO: add weapon conversion to farmwatch/spicebush
/:cl:

2024-04-16 00:43 UTC, Kitsunemitsu commented
>Touches 27 files

2024-04-16 00:46 UTC, Kitsunemitsu requested changes
Small atomization requests just to make merging easier.

2024-04-16 00:46 UTC, Kitsunemitsu commented on ModularTegustation/fishing/code/fish/LC13_fish/saltwater_fish.dm
> +
Going to request atomization for this, it's a small thing that can be merged almost instantly and doesn't really fit in this Gasharpoon PR.

2024-04-16 00:46 UTC, Kitsunemitsu commented on code/modules/clothing/suits/ego_gear/non_abnormality/ucorp.dm
> +/obj/item/clothing/suit/armor/ego_gear/peqod_captain
Same with this, it's a real quick atomization

2024-04-16 00:46 UTC, Kitsunemitsu commented on code/modules/mob/living/simple_animal/abnormality/_tools/zayin/realizer.dm
> +		/obj/item/food/fish/salt_water/tuna_pallid = /obj/item/clothing/suit/armor/ego_gear/realization/gasharpoon,
Ah, the tuna makes sense now. Still will request an atomization that I will merge like ASAP.

2024-04-16 09:50 UTC, vampirebat74 commented
> Small atomization requests just to make merging easier.

As requested, the files regarding the status effect, fish, fixer suit, and realization engine entry to  #2059. It will conflict due to uncommenting for the weapon but that's no big deal.

2024-04-22 02:45 UTC, Kitsunemitsu approved these changes
No massive outstanding issues

2024-04-22 02:45 UTC, merged