Officer Upgrade Injector now 200 PE
vlggms/lobotomy-corp13 pull request #1792
Opened 2024-01-07 00:44 UTC by Ben10083

## About The Pull Request

Officer Upgrade Injector cost now 200 from 400.

## Why It's Good For The Game

Officers are in a odd state where they are both vital to the facility running smoothly, yet also immensely fragile without substantial investment. This PR aims to reduce the cost to invest into officer(s) and allow them to get out of 20 stat hell easier

## Changelog
:cl:
balance: Officer Upgrade Injector now 200 PE
/:cl:

2024-01-07 01:00 UTC, CrabbytheCrab commented
finally I wont spend 10000 pe getting to ex after a records core

2024-01-08 11:59 UTC, EgorDinamit commented
> vital to the facility running smoothly

???

2024-01-24 02:38 UTC, LanceSmites328 requested changes

2024-01-24 02:38 UTC, LanceSmites328 commented on code/datums/quirks/good.dm
What's this doin here

2024-01-24 03:00 UTC, Ben10083 commented on code/datums/quirks/good.dm
https://github.com/vlggms/lobotomy-corp13/pull/1791 Is that, unsure why its shown as changed, did it get changed again?

2024-03-29 18:51 UTC, Kitsunemitsu commented
400 isn't that expensive in the grand scheme of things. Goes double because the EO is in charge of officer injectors.
Along with this, it is still purchased at 400, and both the EO and RO have been enjoying a short renaissance

2024-03-29 18:51 UTC, closed without merging