City of Light Minor Update
vlggms/lobotomy-corp13 pull request #1807
Opened 2024-01-09 10:32 UTC by Kitsunemitsu

## About The Pull Request
Added in the hana machine that prints money
Made minor mapping changes.

## Changelog
:cl:
balance: Hana can now print money
tweak: Plenty of minor mapping updates
/:cl:

2024-01-17 17:36 UTC, Kitsunemitsu commented
Not interested in working on city PRs at the moment.

2024-01-20 00:28 UTC, LanceSmites328 requested changes

2024-01-20 00:28 UTC, LanceSmites328 commented on ModularTegustation/tegu_items/associations/items.dm
> +	to_chat(user, "<span class='nicegreen'>You gain 1 potential!</span>")
This should definitely be a variable that's added up and a message is sent *once*. Also these should be using the new span wrappers.

2024-01-20 00:28 UTC, LanceSmites328 commented on ModularTegustation/tegu_items/associations/machines.dm
>  		to_chat(user, "<span class='notice'>Recommended Grade - [10-grade].</span>")
```suggestion
		to_chat(user, "<span class='notice'>Recommended Grade - [max(10-grade, 1)].</span>")
```

2024-01-20 00:28 UTC, LanceSmites328 commented on ModularTegustation/tegu_items/associations/machines.dm
> +			return
```suggestion
```

2024-02-17 17:39 UTC, Kitsunemitsu commented
This broke. see 1968

2024-02-17 17:39 UTC, closed without merging