Suppression Rewards
vlggms/lobotomy-corp13 pull request #181
Opened 2022-08-20 07:34 UTC by dsmith328

## About The Pull Request
Killing Abnormality grants a maximum of 10 EXP toward a stat dependent on the Abnormality, up to a cap dependent on the Threat Level of said abnormality.  Each Abnormality has a "pool" of exp it rewards to those who assist in its suppression, evenly divided between the participants (assuming they're alive) at the end of the suppression, to a minimum of 1. Should a participant be sufficiently under-leveled for the encounter (Half the stat cap of grinding on the abnormality), they gain double from this suppression. This also applies to Ordeals, turning them into fairly profitable scenarios, assuming you survive it. 

The goal of this is to make Suppressing Abnormalities something that is more likely to occur, as it can benefit the facility beyond just NOT DYING because APPARENTLY, that is NOT enough for people. At the very least, the brave souls who decided to truly Face the Fear will be rewarded for their efforts. All stat rewards are capped at the grinding cap of the abnormality, but this is alterable depending on the individual abnormality. Participants are only counted if they utilize an EGO weapon, as well. Simply punching an Abnormality won't help.

## Why It's Good For The Game
People who actually DO THEIR JOB fall behind nine times out of ten. This is NOT conducive to good gameplay flow. So this should reward them for doing their job, but not encourage farming Abnormalities for EXP via Suppression, as it's almost always worse to let them out for EXP. It'll also help the falling average Employee level due to rising pop

## Changelog
:cl:
add: Suppression Rewards for ALL Abnormalities that breach and ALL Ordeals
/:cl:

2022-08-20 12:51 UTC, EgorDinamit reviewed
No, just no.
I do not think that turning abnormality supression into RPG boss fight with exp as a reward is a good idea.

2023-11-22 00:06 UTC, LanceSmites328 commented
FOR THOUSANDS OF YEARS I HAVE SLUMBERED

2023-11-22 00:11 UTC, TheBronJameOffical commented
sorry pr fuckin _181_???????

2023-11-22 00:11 UTC, LanceSmites328 commented
> sorry pr fuckin _181_???????

FOR **_THOUSANDS_** of years

2023-11-22 00:12 UTC, TaculoTaculo commented
> sorry pr fuckin _181_???????

i know which number to bet on the lottery tomorrow

2023-11-22 10:05 UTC, EgorDinamit requested changes
I hope I don't have to repeat my previous comments.
This is just going to harm the weaker agents even further, making strong agents stronger in the process.

2023-12-06 11:41 UTC, Kitsunemitsu commented
Talking to the entire maintenance team about this. One person isn't going to hold us up.

2023-12-14 13:22 UTC, Kitsunemitsu commented
Egor is not going to merge this PR; no point keeping it open to clutter our PR backlog.

2023-12-14 13:22 UTC, closed without merging

2023-12-14 19:11 UTC, LanceSmites328 commented
For a thousand years I have slumbered and for a thousand more I shall, and in a thousand years you shall cry out for me once more.