Improved arbiter (Adminsbus)
vlggms/lobotomy-corp13 pull request #1929
Opened 2024-02-01 02:48 UTC by Coxswain-Navigator

## About The Pull Request
Adds the ability to toggle damage type to a new "complete" arbiter, as well as several QOL changes including spawners for the various types of arbiters and names for the antagonist panel.

## Why It's Good For The Game
Shouldn't affect players at all but makes life ever so slightly for admins. This was a commissioned feature.

## Changelog
:cl:
admin: gave admins new toys related to arbiters
/:cl:

2024-02-01 02:49 UTC, Kitsunemitsu approved these changes
Yeah sure. Looks good to me, chief.

2024-02-01 03:52 UTC, Gboster-0 commented on code/modules/antagonists/wizard/arbiter.dm
> +		/obj/effect/proc_holder/spell/aoe_turf/singularity
minor nitpick: all of the lists contents should have a comma at the end, even the ending ones
this makes the list look better when being edited in the future on github's lines changed thingy

2024-02-07 05:46 UTC, LanceSmites328 requested changes
rebase for 515 please, everything else is good

2024-02-07 05:54 UTC, LanceSmites328 approved these changes

2024-02-07 05:59 UTC, merged