Batong update
vlggms/lobotomy-corp13 pull request #1934
Opened 2024-02-02 07:24 UTC by Coxswain-Navigator

## About The Pull Request
Adds examine text to agent batons explaining their use, and allows agent batons to deal damage to simple mobs regardless of intent.

## Why It's Good For The Game
Removes a noob trap. Seriously, you spawn with a weapon that has more features to it than most endgame weapons and none of it is explained to you. Why? This changes that.

## Changelog
:cl:
tweak: made agent batons a little bit easier to learn to use
/:cl:

2024-02-02 07:45 UTC, Coxswain-Navigator commented on code/game/objects/items/melee/misc.dm
> +	var/list/readout = list("<span class='notice'><u><b>In order to deal lethal damage with this weapon, you must be on harm intent.</u></b>")
This is underlined and boldened, which makes it much more obvious to players. If you prefer, I can defer to your judgement though.

2024-02-07 05:44 UTC, LanceSmites328 requested changes

2024-02-07 05:44 UTC, LanceSmites328 commented on code/game/objects/items/melee/misc.dm
> +	. += "<span class='notice'>This weapon works differently from most weapons and can be used to disarm other players.</span>"
```suggestion
	. += span_notice("This weapon works differently from most weapons and can be used to disarm other players.")
```

2024-02-07 05:44 UTC, LanceSmites328 commented on code/game/objects/items/melee/misc.dm
> +	. += "<span class='notice'>It has a <a href='?src=[REF(src)];'>tag</a> explaining how to use [src].</span>"
```suggestion
	. += span_notice("It has a <a href='?src=[REF(src)];'>tag</a> explaining how to use [src].")
```

2024-02-07 05:44 UTC, LanceSmites328 commented on code/game/objects/items/melee/misc.dm
> +	to_chat(usr, "[readout.Join()]")
```suggestion
	var/list/readout = list("<u><b>Attacks that are not on harm intent deal nonlethal stamina damage, which will eventually cause humans to collapse from exhaustion.</u></b>")
	readout += "\nAim for a leg to attempt to trip someone over when attacking."
	readout += "\nAim for an arm to attempt to force the target to drop the item they are holding in that hand."
	to_chat(usr, "[span_notice(readout.Join())]")
```

2024-02-07 05:44 UTC, LanceSmites328 commented
Also Rebase for 515. I'd like to see the  Workload run

2024-02-07 05:52 UTC, LanceSmites328 approved these changes

2024-02-07 05:53 UTC, merged