Adds E.G.O Assimilation
vlggms/lobotomy-corp13 pull request #2016
Opened 2024-03-31 10:12 UTC by vampirebat74

## About The Pull Request

What it does on the tin

## Why It's Good For The Game

Should make some things more accessible

## Changelog
:cl:
add: Adds Charles Barkley and the Riblin
imageadd: Adds relevant abnormality portraits
/:cl:

2024-03-31 10:15 UTC, Gboster-0 commented on code/modules/mob/living/simple_animal/abnormality/aleph/barkley.dm
> +	sleep(50)
its clearer how much it waits if you put the SECONDS define there
```suggestion
	sleep(5 SECONDS)
```

2024-03-31 10:18 UTC, Gboster-0 reviewed
those returns are not good

2024-03-31 10:18 UTC, Gboster-0 commented on code/modules/mob/living/simple_animal/abnormality/aleph/barkley.dm
> +	return
don't put returns at the end of code, it automatically puts them there
```suggestion

```

2024-03-31 10:18 UTC, Gboster-0 commented on code/modules/mob/living/simple_animal/abnormality/aleph/barkley.dm
> +	return
don't put returns at the end of code, it automatically puts them there
```suggestion

```

2024-03-31 10:18 UTC, Gboster-0 commented on code/modules/mob/living/simple_animal/abnormality/aleph/barkley.dm
> +	return
don't put returns at the end of code, it automatically puts them there
```suggestion

```

2024-03-31 10:18 UTC, Gboster-0 commented on code/modules/mob/living/simple_animal/abnormality/zayin/riblin.dm
> +	return
don't put returns at the end of code, it automatically puts them there
```suggestion

```

2024-03-31 10:18 UTC, Gboster-0 commented on code/modules/mob/living/simple_animal/abnormality/zayin/riblin.dm
> +	return
don't put returns at the end of code, it automatically puts them there
```suggestion

```

2024-04-02 08:01 UTC, Coxswain-Navigator requested changes
April fools is now over and this now needs a somewhat serious review. Here are some changes I would like made.

2024-04-02 08:01 UTC, Coxswain-Navigator commented on code/modules/mob/living/simple_animal/abnormality/zayin/riblin.dm
This is a joke abnormality so remove its ability to spawn.

2024-04-02 08:01 UTC, Coxswain-Navigator commented on code/modules/projectiles/guns/ego_gun/joke.dm
Change the firing and/or projectile hit sound so it's less annoying and immersion breaking.

2024-04-03 23:04 UTC, Coxswain-Navigator approved these changes
This was made to my specifications, and I approve.

2024-04-03 23:04 UTC, merged

2024-04-03 23:15 UTC, Kitsunemitsu approved these changes
PR Approved, they're all joke abnos.