Limbus Labs Additions
vlggms/lobotomy-corp13 pull request #2047
Opened 2024-04-11 21:34 UTC by tile4

## About The Pull Request
This adds a few things and makes a few changes for abnormalities to make them more RP friendly

- Added Eris, Scorched Girl, Child of the Galaxy and Schad
- Makes Eris leave the brain upon feasting on a body in LCL
- Adds an ability to KoD, Monk, Piscine and Scorched to toggle their sprites to their contained sprites for LCL only.
- Adds an ability for LCL only for Galaxy Child to give gifts and break then, as well as KoD to give her gift
- Makes Monk's panting not play in LCL.
- Add a note to security officers that they are free to talk with abnos when they aren't busy.

## Why It's Good For The Game
More RP stuff is nice for the RP mode.

## Changelog
:cl:
add: Added new things
tweak: tweaked a few things
balance: rebalanced something
/:cl:

2024-04-12 03:13 UTC, Gboster-0 reviewed
mostly nitpicks, one really major thing

2024-04-12 03:13 UTC, Gboster-0 commented on code/modules/mob/living/simple_animal/abnormality/he/galaxy_child.dm
> +datum/action/cooldown/galaxygiftbreak
yeah uh... this is not good
```suggestion
/datum/action/cooldown/galaxygiftbreak
```

2024-04-12 03:13 UTC, Gboster-0 commented on code/modules/mob/living/simple_animal/abnormality/he/pisc_mermaid.dm
> +		/datum/action/innate/change_icon_merm
preferably if you are doing multi-line lists, always have an object end with a comma. It makes future additions look better on github
```suggestion
		/datum/action/innate/change_icon_merm,
```

2024-04-12 03:13 UTC, Gboster-0 commented on code/modules/mob/living/simple_animal/abnormality/teth/scorched_girl.dm
> +		/datum/action/innate/change_icon_scorch
preferably if you are doing multi-line lists, always have an object end with a comma. It makes future additions look better on github
```suggestion
		/datum/action/innate/change_icon_scorch,
```

2024-04-12 03:13 UTC, Gboster-0 commented on code/modules/mob/living/simple_animal/abnormality/waw/clouded_monk.dm
> +		/datum/action/innate/abnormality_attack/toggle/monk_charge, /datum/action/innate/change_icon_monk
please just add another line to this, it looks much better
```suggestion
		/datum/action/innate/abnormality_attack/toggle/monk_charge,
		/datum/action/innate/change_icon_monk,
```

2024-04-12 03:13 UTC, Gboster-0 commented on code/modules/mob/living/simple_animal/abnormality/waw/despair_knight.dm
> +		/datum/action/innate/change_icon_kod, /datum/action/cooldown/knightblessing
```suggestion
		/datum/action/innate/change_icon_kod,
		/datum/action/cooldown/knightblessing,
```

2024-04-24 20:23 UTC, LanceSmites328 requested changes

2024-04-24 20:23 UTC, LanceSmites328 commented on ModularTegustation/tegu_items/limbus_labs/!abno_overwrites.dm
> +		melee_damage_upper = 32
```suggestion
		melee_damage_upper = 32

```

2024-04-24 20:26 UTC, LanceSmites328 submitted a review, later dismissed

2024-04-24 20:26 UTC, LanceSmites328 commented on code/modules/mob/living/simple_animal/abnormality/waw/generalb.dm
> +mob/living/simple_animal/hostile/soldier_bee/Login()
```suggestion
/mob/living/simple_animal/hostile/soldier_bee/Login()
```

2024-04-29 06:55 UTC, Kitsunemitsu commented
Please update the changelog for a quick checklist

2024-04-29 11:09 UTC, tile4 commented
I think that should be good.

2024-05-02 02:07 UTC, Kitsunemitsu approved these changes
Everything here looks good to me. 
Approved.

2024-05-02 02:08 UTC, merged