J Corp Representative
vlggms/lobotomy-corp13 pull request #2141
Opened 2024-05-15 01:46 UTC by tile4

## About The Pull Request
Adds a J corp Representative to the possible representatives you can get. The main gimmicks this rep has is around locking out some of the bad outcomes of RNG, such as increasing the chance to get better loot from gacha, as well as improve chances to get better gear from the well. 

## Why It's Good For The Game
More Representatives is nice to have.

## Changelog
:cl:
add: Added new things
/:cl:

2024-05-15 01:57 UTC, KingSuperBOB commented on code/modules/jobs/job_types/trusted_players/representative.dm
> +datum/outfit/job/representitive/jcorprepresentative
```suggestion
/datum/outfit/job/representitive/jcorprepresentative
```
You forgot to add a /

2024-05-16 05:34 UTC, Gboster-0 commented on ModularTegustation/tegu_items/refinery/crates/_crate.dm
> +				repmodifier += 2
are these chances right?
feels a bit weird that level 3 is the same as 4, and 1 the same as 2

2024-05-18 03:33 UTC, Kitsunemitsu commented
Wait for Crits; this could be epic. Crit build time.

2024-05-19 22:40 UTC, Kitsunemitsu commented
This PR will wait a little longer, as I have some ideas to flesh out J-Corp but it needs more PRs merged first.

2024-06-20 04:25 UTC, InsightfulParasite commented
Assigned kirie since she has a plan for this one and it will make sure it doesnt get lost to the annuls of history.

2024-07-26 22:31 UTC, Kitsunemitsu requested changes
While a little barebones, is a great addition to the game. 
One small change to make and the rest looks fine to me.

2024-07-26 22:31 UTC, Kitsunemitsu commented on ModularTegustation/tegu_items/refinery/crates/_crate.dm
> +			veryrarechance += (repmodifier/4)
I'd prefer is the /4 part is made a variable for each crate.

2024-07-30 22:20 UTC, Kitsunemitsu approved these changes
Looks great to me.
Quite barebones, but what can you do.

2024-07-30 22:20 UTC, merged