God of the seasons rework
vlggms/lobotomy-corp13 pull request #2234
Opened 2024-06-18 02:40 UTC by CrabbytheCrab

## About The Pull Request

Heavily reworks god the of the seasons on breach.
Spring now summons fly traps and mines and can convert dead or insane players into minions
Summer is now a stationary threat that has a powerful slam attack and creates mini volcanos around it
Fall now has a new sprite and summons exploding will-o-wisps
Winter now leaves linger pale damaging mist and can summon frozen spears to strike down its enemies
To compensate for these major reworks I got the say from cox to unnerf the armor and reshuffled the stats a tiny bit
## Why It's Good For The Game

God of the seasons' forms all acting the same was boring.

## Changelog
:cl:
add: new mobs and mechanics for god of the seasons
del: Removed old fall god
balance: unnerfed gots armor and reworked every god form
imageadd: added some icons and images
code: changed some code
/:cl:

2024-06-18 15:13 UTC, Coxswain-Navigator requested changes
Some things need fixing or answering at least.

2024-06-18 15:13 UTC, Coxswain-Navigator commented on code/modules/clothing/suits/ego_gear/aleph.dm
Why does this revert the armor nerf to god of the seasons I did a while back? This thing was nerfed for a reason.

2024-06-18 15:13 UTC, Coxswain-Navigator commented on code/modules/mob/living/simple_animal/abnormality/aleph/seasons.dm
> +		"spring" = list(RED_DAMAGE = 0.8, WHITE_DAMAGE = 0.2, BLACK_DAMAGE = 1.5, PALE_DAMAGE = 1),
Most ALEPH's have 1.2 weakness to a damage type at most, and for good reason. Raising it to 1.5 will make this abnormality too easy to fight.

2024-06-18 15:13 UTC, Coxswain-Navigator commented on code/modules/mob/living/simple_animal/abnormality/aleph/seasons.dm
> +	playsound(src, 'sound/abnormalities/apocalypse/slam.ogg', 100, FALSE, 12)
I'll send you some sound effects you can use for this if you remind me to.

2024-06-18 15:13 UTC, Coxswain-Navigator commented on code/modules/mob/living/simple_animal/abnormality/aleph/seasons.dm
> +	)
Why not save a bunch of lines of code by making this indestructible? And why does it need to be dense?

2024-06-18 15:13 UTC, Coxswain-Navigator commented on code/modules/mob/living/simple_animal/abnormality/aleph/seasons.dm
> +	desc = "What appears to be human, only overgrown and decayed..."
This could use a more apt description, humans are not plants - they cannot be overgrown.

2024-06-18 15:43 UTC, Coxswain-Navigator commented on code/modules/mob/living/simple_animal/abnormality/aleph/seasons.dm
> +	density = TRUE
This doesn't need to be dense, GOTS gets stuck on it.

2024-11-02 19:23 UTC, InsightfulParasite commented
Crabby will this ever be completed or should we just close it down? This is due to recent events.

2024-11-05 22:39 UTC, closed without merging