Adds Forsaken Employee
vlggms/lobotomy-corp13 pull request #2396
Opened 2024-08-20 03:18 UTC by tile4

## About The Pull Request
Adds Forsaken Employee, a new TETH abnormality from Limbus that has a breach that will overload all the lights in a random hallway or department room on breach.

## Why It's Good For The Game
More abnormalities

## Changelog
:cl:
add: Added Forsaken Employee
imageadd: added Forsaken Employee images
/:cl:

2024-08-24 04:34 UTC, Kitsunemitsu commented
Willing to try this, maybe we can work something more into it.

2024-08-27 02:38 UTC, InsightfulParasite commented
Test Merged 8/26/24

2024-09-01 20:41 UTC, Coxswain-Navigator commented
Mechanically speaking this is annoying, if sound. I think destroying all of the lights is a bit much for something of such a low risk level. It would be ideal if it instead turned off the lights for a few minutes. Sometimes there just aren't clerks willing to fix everything up. My only other concern is that it is a bit boring. There is no sound effect or really any other indicator of what it is doing besides some flavor text.

2024-09-02 02:47 UTC, Kitsunemitsu commented
I did recommend a rework to do with PE; talking with them about it

2024-09-04 13:58 UTC, Kitsunemitsu commented
Please fix your comments.

2024-09-14 16:35 UTC, Coxswain-Navigator requested changes

2024-09-14 16:35 UTC, Coxswain-Navigator commented on code/game/objects/items/ego_weapons/teth.dm
This ego weapon doesn't seem all that practical at all. At the beginning of a round (when TETH is used by agents) it is practically useless, at the end (when quota is met) It's just an amazing weapon... for clerks.  Why?

2024-09-15 03:46 UTC, tile4 commented on code/game/objects/items/ego_weapons/teth.dm
God, I don't even know what the hell I was thinking when I made that formula... Hopefully this one would be more reasonable.

2024-10-01 21:48 UTC, tile4 commented
This PR got screwed thanks to a mistake I made when rebasing so I readded the stuff into #2457 to start with a fresh slate I guess.

2024-10-01 21:48 UTC, closed without merging