Adds Enkephalin Rush
vlggms/lobotomy-corp13 pull request #2454
Opened 2024-10-01 18:35 UTC by vampirebat74

## About The Pull Request

Adds a new exploration-focused experience that brings traditional ss13 sandbox elements together. You and your staff must recover a buried Lobotomy Corporation branch, with an objective to restore its functionality. However, the facility is unstable and experiences occasional earthquakes instead of your ordeals, which may unveil **uninvited guests** within the rubble. Your primary goal is to secure the **golden bough** at the bottom of this facility, as well as the **abnormalities** who've escaped. 

This map will additionally feature an outdoor area where a secondary group of players will seek escaped abnormalities whose influence has bled onto the city's landscape.

- May include roles other than Lobotomy Corporation.
- Company equipment and city equipment-focused, rather than E.G.O
- Abnormality cores must be brought to fill containment cells,  rather than them arriving over time.
- Mining and engineering
- Away missions
- Fight your way through an abandoned L corp facility!

## Why It's Good For The Game

This serves as an attempt to combine the primary game loop with the mining gameplay you'd typically see in other servers, as well as some minor engineering work for those who are willing to invest the effort.

## Changelog
:cl:
add: Added new things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

2024-12-08 00:19 UTC, Tokanova commented
Can you make it so Abnos don't spawn over time? That's one of the issues I saw during the tests.

2024-12-08 00:29 UTC, vampirebat74 commented
> Can you make it so Abnos don't spawn over time? That's one of the issues I saw during the tests.

That's a bug, they are not supposed to spawn over time. There's a code snippet for it under maptype.dm that didn't seem to work on the live server.

2025-03-04 21:49 UTC, vampirebat74 commented
Putting a self-reminder here to remove the abnormality changes from the PR before review

2025-04-08 03:53 UTC, Kitsunemitsu commented
Currently revivewing!

2025-04-12 16:31 UTC, Kitsunemitsu requested changes
Mostly minor changes requested.

2025-04-12 16:31 UTC, Kitsunemitsu commented on ModularTegustation/tegu_items/enkephalin_rush/enkr_treasure.dm
> +	. = list("<span class='notice'><i>On closer examination, [src] appears to be an agate fishook.</i></span>")
Use span_notice()

2025-04-12 16:31 UTC, Kitsunemitsu commented on ModularTegustation/tegu_items/enkephalin_rush/landmarks.dm
> +GLOBAL_LIST_INIT(assiyah, list(//HE's and TETHs
After merge we can expand this.

2025-04-12 16:31 UTC, Kitsunemitsu commented on ModularTegustation/tegu_items/enkephalin_rush/objective.dm
> +	if(do_after(user, 10 SECONDS))
Better to swap this to !do_after > return

2025-04-12 16:31 UTC, Kitsunemitsu commented on code/modules/jobs/job_types/suppression.dm
> +	mapexclude = list("enkephalin_rush")
This doesn't need to be here, for ERAs to spawn, a DO has to spawn first.

2025-04-13 05:08 UTC, vampirebat74 commented on ModularTegustation/ego_weapons/melee/aleph.dm
> +/obj/item/ego_weapon/mining/smile
I'm not sure what you mean by this. Would you prefer that I make a variable of E.G.O weapons that determines whether or not it can be used to mine? Toolspeed and tool behavior are variables of /item/ and making a "miningspeed" variable would just complicate the digging process.

2025-04-13 05:10 UTC, vampirebat74 commented on ModularTegustation/tegu_items/enkephalin_rush/enkr_corpses.dm
> +/obj/effect/mob_spawn/human/agent/loot/teth
These corpses are random, but they only spawn with E.G.O based on abnormalities present. It's a bit rustic (doesn't check abnocores) but gives the facility more of a lived-in feel. The subtype /agent/randomloot is a purely random one based on wishing well, but I've disabled it from spawning as I couldn't get it to generate properly.

2025-04-13 20:48 UTC, vampirebat74 commented on ModularTegustation/ego_weapons/melee/aleph.dm
> +/obj/item/ego_weapon/mining/smile
Discussed over discord, the mining subtype has been removed in favor of a simpler process.

2025-04-16 11:20 UTC, Kitsunemitsu commented
In accordance with the current Developer ordinance: https://discord.com/channels/982658747304378520/982658749049221136/1362024047357071490

I can 100% confirm that this passed checks before my one line code cleanup.

2025-04-16 11:21 UTC, merged