Reverts jbird to livinginrange
vlggms/lobotomy-corp13 pull request #2478
Opened 2024-10-12 08:06 UTC by KingSuperBOB

## About The Pull Request
urange does not pierce rhinos, livinginrange does, piercing is needed on a abno which is in the piercing slot

## Why It's Good For The Game
Makes judgement bird fulfill its purpose in other modes

## Changelog
:cl:
add: Added new things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

2024-10-13 01:42 UTC, Kitsunemitsu requested changes

2024-10-13 01:42 UTC, Kitsunemitsu commented on code/modules/mob/living/simple_animal/abnormality/waw/judgement_bird.dm
> +	for(var/mob/living/L in livinginrange(judgement_range, src))
Agonizing and significantly more laggy, This won't do for now; Please try to find another way. There is a ways to make damage pierce rhinos I just forgot what it was

2024-10-27 06:01 UTC, KingSuperBOB commented
Making a second attempt at this pr, this time Im going for this abomination of a else statement as it was a suggested solution

2025-01-14 17:18 UTC, Kitsunemitsu approved these changes
Fuck it, still shitcode. But it's less shitcode than before.

2025-01-19 08:47 UTC, Kitsunemitsu commented
Updated in Endermage's PR

2025-01-19 08:47 UTC, closed without merging