Expanded Rhino Captain arsenal
vlggms/lobotomy-corp13 pull request #2531
Opened 2024-11-02 21:10 UTC by KingSuperBOB

## About The Pull Request
Two new captain rhinos which are randomized roundstart, rhino captain mechs now need specifically rhino captain access, slight light rhino buff, rhino belt for error repairs, removal of rhino acid armor.

## Why It's Good For The Game
Further round variety, light rhinos are now slightly viable, low ranking pilots dont steal captain mechs, rhinos can now fix the fire burning them alive and xenos can now actually kill rhinos.

## Changelog
:cl:
add: Melee Captain Rhino, Heavy captain rhino, Rhino belts
tweak: Rhino Captain is a actual thing instead of a var edit
balance: all rhinos have acid armor 0, Durand gone from VII/VII/VII/I to V/V/V/I
mapping: removed rhino pilot gear from the map, removed var edited captains rhino, added randomize spawner for captain rhino
/:cl:

2024-11-02 21:50 UTC, KingSuperBOB commented
Will need to fix linters

2024-11-02 23:45 UTC, Gboster-0 commented on ModularTegustation/tegu_items/rcorp/itemspawner.dm
> +	..()
Do not leave initialize without a return hint, always do eighter `. = ..()`, `return ..()` or sometimes `return INITIALIZE_HINT_[insert case here]`
```suggestion
	. = ..()
```

2024-11-09 18:03 UTC, Kitsunemitsu requested changes
The durand shield is infinite and makes it invincible lol

2024-11-10 00:50 UTC, KingSuperBOB commented
Durand shield given 15 second cooldown

2024-11-28 02:08 UTC, Kitsunemitsu approved these changes
Fixed ya spelling mistake G.

This looks good, if not great.
Rcorp is in for a buff and this is a great way to do it!

2024-11-28 02:10 UTC, merged