The Shrimp Association Executive
vlggms/lobotomy-corp13 pull request #254
Opened 2022-09-01 10:36 UTC by Kitsunemitsu

## About The Pull Request
Adds in a wellcheers aberration, Shrimp Association Executive.
How he works is that he requests a worktype, and then if you do that worktype, you get a work boost.
On good work, he gives you extra equipment for clerks to use lategame or maybe a spawn grenade to spawn helpers.
 

## Why It's Good For The Game
**This PR was requested by InsightfulParasite.**
He has been working very hard, and I want to make an abnormality that he helped design.

## Changelog
:cl:
add: Added The Shrimp Association Executive
/:cl:

2022-09-03 07:09 UTC, dsmith328 requested changes
Double Check your images and fix the EGO Armor from the console. Honestly, I don't think you'd need to manually add a weapon or at the very least you could have his "weapon" be the base Soda EGO gun, with the real ones gained via work. You could probably have the EGO Gift as a Tie as well.

2022-09-03 07:32 UTC, Kitsunemitsu commented
Ego armor fixed, He's been given a golden soda pistol that costs 50 PE but is exactly the same in every other way.

2022-09-03 19:50 UTC, dsmith328 requested changes
Besides this, most of it seems good

2022-09-03 19:50 UTC, dsmith328 commented on code/datums/abnormality/_ego_datum/waw.dm
>  	item_path = /obj/item/clothing/suit/armor/ego_gear/loyalty
You deleted the cost for Loyalty here.

2022-09-05 21:11 UTC, dsmith328 approved these changes

2022-09-05 21:11 UTC, merged