Weaving Lindworm
vlggms/lobotomy-corp13 pull request #2565
Opened 2024-11-19 04:54 UTC by Kitsunemitsu

## About The Pull Request
Adds Weaving Lindworm.
This is an abnormality that has the theme of "Shedding armor" so that it loses it's defenses.
Instead of dying, lindworm releases a damage turf range. It also does this on attack.
It then sheds it's skin and heals to full. It deals this one time per layer, and starts with 5 layers

Lindworm actually lowers the defenses of the person who worked on it, based off what was worked on it.
To encourage this, Lindworm has quite high work rates; with each work, and lowers it's own layers per work.

It's EGO gear however, is very strong. While it has a low attack rate, and stuns you on attack, it also rends both red and white.
All on top of 4 range, making it an excellent support weapon.

## Changelog
:cl:
add: Added Weaving Lindworm
/:cl:

2024-11-20 03:05 UTC, Tokanova commented on code/modules/clothing/suits/ego_gear/waw.dm
Only Be Becoming? Was that supposed to be Only by becoming?

2025-01-14 03:01 UTC, InsightfulParasite commented on code/modules/mob/living/simple_animal/abnormality/waw/lindworm.dm
> +	if(ishuman(target))
Your going to want to put a CanTarget override for non humans. Currently the stat attack applies to simplemobs and causes the lindworm to attack ordeal corpses.
Essentially just put in 
/mob/living/simple_animal/hostile/abnormality/lindworm/CanAttack(atom/the_target)
	if(isliving(the_target))
		var/mob/living/carbon/host = the_target
		if(host.stat == DEAD && !ishuman(the_target))
			return FALSE
	return ..()

2025-01-14 03:02 UTC, InsightfulParasite commented on code/modules/mob/living/simple_animal/abnormality/waw/lindworm.dm
> +	if(ishuman(target))
Actually it might be easier to do it backwards and remove the stat_attack and just put in a can_attack override for dead humans.

2025-02-19 02:04 UTC, Kitsunemitsu commented on code/modules/mob/living/simple_animal/abnormality/waw/lindworm.dm
> +	if(ishuman(target))
Was fixed!

2025-02-19 02:09 UTC, tile4 requested changes
The paperwork says the counter decreases on bad works but I don't see it in the actual code for the abno.

2025-08-10 22:48 UTC, closed without merging