Blue smocked shepherd can now lie
vlggms/lobotomy-corp13 pull request #281
Opened 2022-09-06 18:24 UTC by Caldony

## About The Pull Request
Whenever a work on shepherd is finished, he will have a 30% chance of lying and 70% chance of saying the truth, as of now shepherd is only capable of mentioning people's death/life or if an abnormality is breaching/contained
originally I wanted to make it a 50% chance of lying, however him saying the truth _most_ of the time means the lies are more likely to be believed.

I haven't coded in a while, so do expect some shitcode and really hacky solutions. But there isn't any runtime and it accounts for most scenarios in which the lies are relevant so there shouldn't be any problems functionally.

## Why It's Good For The Game
A huge part of shepherd personality in WL is the fact that he's constantly mixing truth with lies,  that feature not only gives him some personality but it can also make people a little bit more paranoid as to what has and hasn't breached or who is and isn't dead, it's mostly flavour though.

## Changelog
:cl:
add: Shepherd is now capable of lying 
/:cl:

2022-09-07 16:00 UTC, EgorDinamit commented on code/__DEFINES/dcs/signals.dm
> +#define COMSIG_GLOB_ABNORMALITY_SPAWN "!abno_datum"
```suggestion
#define COMSIG_GLOB_ABNORMALITY_SPAWN "!abno_spawned"
```
abno_datum is rather confusing for a signal name.

2022-09-07 16:01 UTC, EgorDinamit commented on code/modules/mob/living/simple_animal/abnormality/he/blue_shepherd.dm
> +				"'s hasn't breached yet, but I wouldn't count on it staying that way.",
```suggestion
				" hasn't breached yet, but I wouldn't count on it staying that way.",
```

2022-09-07 16:06 UTC, EgorDinamit requested changes
1. It'd be a better idea to not create an entirely new list that does same thing as existing ones. Just use global lists.
2. Procs should be using camel case, i.e. "OnNewCrew()" instead of "on_new_crew". It is the opposite for variables.

2022-09-07 17:58 UTC, Caldony commented
I did most of the change asked with a slight difference
1. I didn't end up using the custom abno list as I could in fact just use the global datum list at each work, that does mean there is now no use for the abno spawn global signaller, I can delete it if you want since it currently serves no purpose but I still think it's a useful signaller to have around
2. I kept the people list but slightly changed how it work, while I CAN use the global living list, I realised that people respawn very often which means there's inevitably going to be duplicate names, which means the list will probably be bloated by dead versions of someone, so whenever a new crewmember that has the same name of someone already in the list joins it gets deleted to avoid useless duplicate, while still acknowledging dead people as long as they haven't already respawned

2022-09-07 19:25 UTC, EgorDinamit commented
There is a global list of players which excludes dead people and mobs with no clients.

2022-09-07 21:49 UTC, Caldony commented
that has a different issue in that if I search this list whenever a work is complete, then it won't include dead people, which defeats the point

2022-09-10 19:25 UTC, dsmith328 commented
I've seen this in practice and it's honestly great having people double check over radio what abnos have breached when Blue Smocked talks some shit just after a meltdown.

2022-09-11 13:40 UTC, Caldony commented
fuck I messed up the commit squash hold on fuck

2022-09-11 13:40 UTC, closed without merging