Censor EGO nerf
vlggms/lobotomy-corp13 pull request #283
Opened 2022-09-07 07:02 UTC by TemperanceTempy

## About The Pull Request

Nerfs Censors damage resist and fixes reduction applying while not equipped in the hand.

## Why It's Good For The Game

local crackhead makes 3 censored ego and starts facetanking multiple pale apostles. That probably shouldn't happen.
## Changelog
:cl:
balance: reduced damage reduction from 40% to 10% as this applies alongside armor calculation
fix: fixed damage reduction still applying when weapon was moved from the hand to other inventory slots.
/:cl:

2022-09-07 16:08 UTC, EgorDinamit commented
Nuh-uh, it is a 250 PE weapon from a highly dangerous abnormality. It deserves to be strong.
If it, for some reason, allows users to stack it more than twice(humans have two hands), then it's a bug that should be fixed instead.

2022-09-08 02:53 UTC, Kitsunemitsu commented
Egor, Censored is an issue as a weapon.
You should NOT be able to get 80% resistances across everything because you "worked on a kinda hard abnormality"

It should have it's resistances removed entirely, and the damage on the IFF special attack reduced to 120.
It should NOT be objectively better than Paradise lost and Twilight.

2022-09-08 05:41 UTC, EgorDinamit requested changes
Remove armor buff. Nothing else is to be changed.

2022-09-14 03:09 UTC, dsmith328 commented
Removed the "Do Not Merge" tag because we've literally talked about adding this exact change into the game and confirmed it should be added.

2022-09-14 05:35 UTC, EgorDinamit commented on code/game/objects/items/ego_weapons/aleph.dm
> -/obj/item/ego_weapon/censored/get_clamped_volume()
Bring it back, this makes the attack sound less loud.

2022-09-14 05:36 UTC, EgorDinamit commented
> Removed the "Do Not Merge" tag because we've literally talked about adding this exact change into the game and confirmed it should be added.

For future reference, I'd recommend against removing it since it's specifically for use by head coder(currently me).

2022-09-14 06:09 UTC, killer7luis commented
ngl instead of lowering it to 10% how about 20%?

2022-09-14 11:32 UTC, Kitsunemitsu commented
Yeah instead of a free immunity ypu get a free executive armor that stacks with other armor :clueless:. The problem is that it has this ability. Free armor just for carrying a weapon that stacks additively to the other stuff.

2022-09-14 13:01 UTC, EgorDinamit approved these changes

2022-09-14 13:01 UTC, merged