Laetitia Rework
vlggms/lobotomy-corp13 pull request #382
Opened 2022-10-24 05:04 UTC by PotatoTomahto

## About The Pull Request

Changes how Laetitia's prank works.
- 70% to gain the gift on Neutral is unchanged
- 30% to remove gift on Good work, 15% to remove gift and 15% to begin explosion on Neutral, 70% to begin explosion on Bad
- If you work another abnormality with the gift, the explosion timer is halved
- Randomed gift timer between 3 to 4 minutes
- If you have Prudence 60, you get at most a 10 second warning before explosion.
- If you have Prudence 80, you are notified when you get the gift.

Added gift message and a neat indicator as a warning

Adds info to records, fixes consistency of some HE records.
## Why It's Good For The Game
Her prank used to be a 200 damage that was given out at a high chance, forcing people to stop their entire grind and wait it out with red armor. Because this was way too unpredictable and punishing, she was rarely chosen and worked significantly less than other HEs. This PR is designed to give people a chance to deal with and react to the prank, while still keeping the RNG surprise element. 
Laetitia is now an abnorm that punishes you if you're given her gift and work other abnorms, while also encouraging players to continue working her. Basically, be ready to keep working with her if you get a neutral ~~because she's a good girl who does nothing wrong~~.

## Changelog
:cl:
tweak: laetitia
:cl:

2022-10-24 13:01 UTC, Kitsunemitsu commented
Remove the warning time, it should be a jumpscare.

2022-10-24 13:02 UTC, Kitsunemitsu requested changes
See above comment.

2022-11-01 02:06 UTC, Kitsunemitsu commented
Waiting on the rework from REDACTED, honestly. IDK Why you didn't wait until his PR was merged like I recommended.

2022-11-04 14:35 UTC, EgorDinamit commented on code/modules/mob/living/simple_animal/abnormality/he/laetitia.dm
> +			RegisterSignal(user, COMSIG_WORK_STARTED, .proc/WorkCheck)
That signal should probably go to the status effect itself.

2022-11-17 17:58 UTC, EgorDinamit commented on code/modules/mob/living/simple_animal/abnormality/he/laetitia.dm
> +/datum/status_effect/pranked/tick()
Shouldn't there be parent call?

2022-11-17 17:58 UTC, EgorDinamit commented on code/modules/mob/living/simple_animal/abnormality/he/laetitia.dm
> +/datum/status_effect/pranked/on_remove()
Same here. Missing parent call, I assume.

2022-11-17 18:00 UTC, EgorDinamit commented on code/modules/paperwork/records/info/waw.dm
> -/obj/item/paper/fluff/info/waw/alriune
You accidentally deleted records...

2022-11-17 20:19 UTC, dsmith328 commented on code/modules/mob/living/simple_animal/abnormality/he/laetitia.dm
> +	if(duration < world.time) //if prank removed due to it expiring
`<=` might be better here

2022-11-17 20:43 UTC, dsmith328 commented on code/modules/paperwork/records/info/he.dm
> +	- When an employee enters attempts work while the Counter is at 1, they would immediately die. Afterwards, the Qliphoth counter decreased and the Woodsman began searching for hearts.    <br>
please remove the word `enters`

2022-11-17 20:45 UTC, dsmith328 commented on code/modules/paperwork/records/info/waw.dm
> -/obj/item/paper/fluff/info/waw/alriune
See now it's gone... forever gone!

2022-11-18 07:03 UTC, EgorDinamit submitted a review, later dismissed

2022-12-01 13:01 UTC, EgorDinamit approved these changes

2022-12-01 14:22 UTC, Kitsunemitsu approved these changes
Yeah if it's 10 seconds it's good.
I approve this from a balance perspective

2022-12-01 15:27 UTC, merged