Helper Work Made Accurate
vlggms/lobotomy-corp13 pull request #475
Opened 2022-11-19 09:13 UTC by PotatoTomahto

## About The Pull Request
- Starting qliphoth lowered to 2
- Good work no longer increases qliphoth
- Normal work now has 40% probability to lower qliphoth, bad work has 80% instead of guaranteed
- Added gift message

## Why It's Good For The Game
Why was reddit so easy to contain before? This makes it accurate to LC and an actual HE threat.

## Changelog
:cl:
tweak:  all-around-helper 
:cl:

2022-11-19 09:18 UTC, EgorDinamit commented on code/modules/mob/living/simple_animal/abnormality/he/helper.dm
> +	gift_message = "Contamination scan complete. Initiating cleaning protocol."
I'd rather you not change it everywhere. The message appears when someone receives the gift, it should be as simple as "You have received the gift from X" for most abnormalities.

2022-11-19 09:18 UTC, EgorDinamit commented on code/modules/mob/living/simple_animal/abnormality/he/helper.dm
> -/* Work effects */
Why delete the comment?

2022-11-19 09:19 UTC, EgorDinamit commented on code/modules/mob/living/simple_animal/abnormality/he/helper.dm
> +	if(prob(80))
Why add a chance here?

2022-11-21 13:16 UTC, Kitsunemitsu requested changes
Update records. It is not optional.

2022-11-23 15:25 UTC, Kitsunemitsu approved these changes
Approved.

2022-11-24 08:51 UTC, merged