bun bun!
vlggms/lobotomy-corp13 pull request #498
Opened 2022-11-29 00:36 UTC by killer7luis

## About The Pull Request

This adds a 1% chance of a bunnygirl sprite appearing instead of the training bunny dummy

## Why It's Good For The Game

Its cute :>

## Changelog
:cl:
add: Bunny training dummy girl
:cl:

2022-11-29 00:41 UTC, monochromatism approved these changes
Yes.

2022-11-29 00:51 UTC, dsmith328 reviewed
While I like the art, I'm uncertain about how well it would fit into the game as a whole. Be it pose or just overall. I'm asking @EgorDinamit to review this.

2022-11-29 01:13 UTC, killer7luis commented
Btw if you dont like that ver i can change the sprite 
![Bungal but not booba preview](https://user-images.githubusercontent.com/84632338/204414105-a0aea34e-a3a6-4953-b653-6ff0fefbd0ba.gif)
into this

2022-11-29 02:19 UTC, killer7luis commented
![Bungalemergencypreview](https://user-images.githubusercontent.com/84632338/204422686-32569692-3d18-49cf-b6aa-2bd7b66a7c3a.gif)
Here's also this version just in case

2022-11-29 03:09 UTC, Kitsunemitsu requested changes
I will also not be the one to approve this in code, but I approve it in my soul.
Also change the pixel_x to 32 on sprite change

2022-11-29 03:14 UTC, killer7luis commented
How do i do that?

2022-11-29 18:55 UTC, Kitsunemitsu reviewed
I'm not going to be the one to approve this in code, but I approve it in my heart.

2022-11-30 00:11 UTC, killer7luis commented
The changes chu asked are done

2022-12-01 09:58 UTC, EgorDinamit commented on code/modules/mob/living/simple_animal/abnormality/teth/training_rabbit.dm
> +/mob/living/simple_animal/hostile/abnormality/training_rabbit/Initialize()	//1 in 100 chance for bunny girl waifu
Move Initialize proc directly below mob's definition.

2022-12-02 15:52 UTC, killer7luis commented
changes doneee

2022-12-11 10:48 UTC, EgorDinamit approved these changes

2022-12-11 10:48 UTC, merged