Adds Random Roll buttons for Queue Console
vlggms/lobotomy-corp13 pull request #520
Opened 2022-12-13 10:45 UTC by Cupax3

## About The Pull Request
Adds "Let's Roll":
Picks randomly from the list of abnormalities in the possible abnormalities.
Adds "Fuck It Let's Roll":
Picks randomly from all abnormalities in the unlocked levels. Locks all consoles afterwards to prevent metagaming.
Adds "Hardcore Fuck It Let's Roll":
Picks randomly from all levels. Locks all consoles afterwards to prevent metagaming.
Refactors some code to their own procs, adds some helper procs to SSabnormality_queue

## Why It's Good For The Game
~~it isnt???~~
<details>
<summary>CHAOS CHAOS</summary>

https://www.youtube.com/watch?v=Z01Tsgwe2dQ

</details>

## Changelog
:cl:
add: The Abnormality Queue console can now do the Manager's job for them!
refactor: Cleaner queue console code, more SSabnormality_queue helper procs
/:cl:

2022-12-13 10:54 UTC, Cupax3 commented
I HATE MAX LINE LENGTH LINTING
I HATE MAX LINE LENGTH LINTING
I HATE MAX LINE LENGTH LINTING

2022-12-13 11:03 UTC, Cupax3 commented
THE LINTER GOD IS APPEASED PRAISE THE SUN

2022-12-13 20:46 UTC, Kitsunemitsu commented
Going to test this for a bit in any case.

2022-12-13 22:22 UTC, Kitsunemitsu approved these changes
Works very well, if anything I'd change it from "Let's rock" to "We ball

2022-12-13 23:49 UTC, Cupax3 commented
hi i just saw that the subsystem never clears its own flag that the pick was forced its ineffectual tight now but could be a bug in the future so dont merge pls ill push a fix tomorrow

2022-12-14 14:05 UTC, Cupax3 commented
> hi i just saw that the subsystem never clears its own flag that the pick was forced its ineffectual tight now but could be a bug in the future so dont merge pls ill push a fix tomorrow

done

2022-12-15 12:29 UTC, EgorDinamit commented on code/controllers/subsystem/abnormality_queue.dm
> +	var/fucked_it_lets_rolled = FALSE
Is there any reason for this to exist?

2022-12-15 12:29 UTC, EgorDinamit requested changes
There's no need for new variable to lock consoles;
Just make hardcore roll change the list of available abnos to only one, so it cannot be changed.

2022-12-15 23:36 UTC, SpaceJohn413 commented
**FUCK IT WE BALL**
**FUCK IT WE BALL**
**FUCK IT WE BALL**
**FUCK IT WE BALL**

2022-12-17 12:00 UTC, Cupax3 commented
> There's no need for new variable to lock consoles;
> Just make hardcore roll change the list of available abnos to only one, so it cannot be changed.

I consider locking consoles to be a feature - for admin usage or future content that might require it.
If you'd still like me to remove it, please reply.

2022-12-18 07:53 UTC, Cupax3 commented
Actually
locking is kinda required because without it, you could re-press the roll buttons.
The option you mention is also already implemented via the new helper proc SSabnormality.ClearChoices()
I see nothing in the additions that is truly pointless - even the flag on the subsystem itself is a useful piece of knowledge as "There are no picks" is not always interchangeable with "This was rerolled".

2022-12-18 11:45 UTC, EgorDinamit submitted a review, later dismissed

2022-12-18 12:17 UTC, Cupax3 commented
found an incorrect indendation e

2022-12-20 23:42 UTC, dsmith328 approved these changes
You know what, I think this is the greatest fucking Litmus test for managers and I'm not gonna specify *why*

2022-12-21 14:49 UTC, EgorDinamit approved these changes

2022-12-21 14:50 UTC, merged