Record and abnorm names changed for consistency
vlggms/lobotomy-corp13 pull request #543
Opened 2022-12-21 23:29 UTC by PotatoTomahto

## About The Pull Request
Fixes all records' grammar and diction to be consistent and follow the LobCorp writing style. 
Records now follow these resistance intervals:
- Absorbs: -X
- 0 - Immune
- (>0 - 0.5 : Resistant)
- (>0.5 - <1 : Endured)
- 1 : Normal
- (>1 - <1.5 : Weak)
- 1.5 - <2 - Vulnerable
- 2 - Fatal

Adds "The" to certain abnorms' names and changes Rose messages to be more distinct.
Fixes brute resistance on Snow White Apple.
Adds some tips

Adds Behavior Adjustment records.

## Why It's Good For The Game
Because I'm a nitpicking nerd.

## Changelog
:cl:
additions: tips
tweak: records
tweak: abnorm names and rose messages
fix: snow white apple brute resist
/:cl:

2022-12-22 04:17 UTC, Kitsunemitsu requested changes

2022-12-22 04:17 UTC, Kitsunemitsu commented on code/modules/paperwork/records/info/he.dm
> -	- Blue Smocked Shepard mercilessly attacked everyone in the area. <br>
This is here to mention that Blue Shep is a neutral mob and that it's not strictly a bad thing to release it.

2022-12-22 04:17 UTC, Kitsunemitsu commented on code/modules/paperwork/records/info/he.dm
> +	- While breached, The Watchman flooded the surrounding area with darkness. This darkness had the same propogation properties as light.<br>
"Propagation" already describes a specific property.

2022-12-22 04:17 UTC, Kitsunemitsu commented on code/modules/paperwork/records/info/teth.dm
> +	- When the work result was Bad, the Qliphoth Counter lowered.	<br><br>
No mention of 0 qliphoth

2022-12-22 04:17 UTC, Kitsunemitsu commented on code/modules/paperwork/records/info/tools.dm
> +	- The employee who drops something precious into the well will receive a gift. <br>
Specify EGO or ahn please to remove ambiguity on what can be put in

2022-12-22 04:17 UTC, Kitsunemitsu commented on code/modules/paperwork/records/info/waw.dm
> +	- When employees of Justice Level 3 or lower finished working with The Warden, the Qliphoth Counter lowered.	<br>
It's not an "Or" it's an "And". Both have to be below level 4.

2022-12-22 04:17 UTC, Kitsunemitsu commented on code/modules/paperwork/records/info/waw.dm
> +	- After 2 employees died within the facility, the Qliphoth Counter decreased.	<br>
Only takes one person now. Records were not updated.

2022-12-22 04:17 UTC, Kitsunemitsu commented on code/modules/paperwork/records/info/waw.dm
> +	- When the Qliphoth Counter reached 0, a shrimp strike force arrived at Shrimp Association Executive’s location.	<br>
Now arrives in main rooms.

2022-12-22 04:17 UTC, Kitsunemitsu commented on code/modules/paperwork/records/info/waw.dm
> +		<li>Shrimp Corporation branded firearms</li>
"Shrimp Corporation" Brand Firearms is grammatically correct.

2022-12-22 04:17 UTC, Kitsunemitsu commented on code/modules/paperwork/records/info/waw.dm
> +		<li>Wellcheers soda</li>
"A can of Wellcheers-Brand soda" fits better here, as it does not assume that the reader knows what wellcheers is

2022-12-22 04:17 UTC, Kitsunemitsu commented on strings/tips.txt
> +Big Bird's Qliphoth Counter will reduce every time 2 people die in the facility.
Just one now

2022-12-22 15:21 UTC, Kitsunemitsu commented on code/modules/paperwork/records/info/waw.dm
> +	- When employees of Justice Level 3 or lower finished working with The Warden, the Qliphoth Counter lowered.	<br>
I know, but the way it's written is "If your justice is 3 or lower, Q lowered." and "If your fort is 3 or lower, Q lowered." 
It should be  "If your fort and justice are both 3 or lower, Q lowered"

2022-12-22 15:22 UTC, Kitsunemitsu commented on code/modules/paperwork/records/info/he.dm
> -	- Blue Smocked Shepard mercilessly attacked everyone in the area. <br>
I only request this because you can release Blue Shep on purpose.

2022-12-22 15:22 UTC, Kitsunemitsu commented on code/modules/paperwork/records/info/aleph.dm
> +	- The music that is played by The Silent Orchestra when it escapes consists of 4 Movements. As the piece progresses, the employees listening will suffer WHITE damage and the size of the audible area
wack

2022-12-25 03:12 UTC, Kitsunemitsu submitted a review, later dismissed

2023-01-04 11:45 UTC, EgorDinamit commented on code/modules/paperwork/records/info/aleph.dm
> +	Name : WhiteNight<br>
?

2023-01-04 11:47 UTC, EgorDinamit commented on strings/sillytips.txt
> +Stop teaching NT bad words.
Claw is somewhat of a spoiler for new players(those that won't get to core suppression), idk how I feel about adding it to the tips.
"Bongbriter". So it is brittish?
WCCA tip feels obsolete and says nothing.

2023-01-24 09:33 UTC, EgorDinamit commented on code/modules/mob/living/simple_animal/abnormality/zayin/bald.dm
> +	name = "You’re Bald..."
Why? Just keep it as is.

2023-01-28 10:59 UTC, EgorDinamit approved these changes

2023-01-28 10:59 UTC, merged