Bankrupt Employees, Remove Barriers, and Revival Pens
vlggms/lobotomy-corp13 pull request #577
Opened 2023-01-27 03:10 UTC by InsightfulParasite

## About The Pull Request
Pens are a remnant of Lobotomy Corp Alpha, a form of healing that is more effective than it is worth.
RP Reason: Lobotomy corp HQ is requesting more branches and that means funding is spread thin.

## Why It's Good For The Game
No one cares about clerks. Also makes things that counter pale damage more rare and valuable.

## Changelog
:cl:
tweak: Reduces initial money to 0
tweak: remove barriers and revival pens from clerks.
/:cl:

2023-01-27 09:33 UTC, Kitsunemitsu commented
Why are you removing money?

2023-01-27 10:55 UTC, EgorDinamit requested changes
Rename and make new paycheck defines for our jobs.
Not sure how I feel about starting money being zero, since we still have plenty of vendors(notably botany) that ask for money.
You also only removed medipens from clerks(which is good); Planning to do the same throughout every map?

2023-01-27 11:02 UTC, Kitsunemitsu commented
Removing medipens is a large meta shift right before _we were going to remove them anyways._ Just a heads up, cargo UI code is done and when i am done being sick and fixing my PRs I will probably do cargo.

2023-02-07 16:16 UTC, EgorDinamit approved these changes

2023-02-07 16:16 UTC, merged