Bare Metal and Alleyway EGO abilities
vlggms/lobotomy-corp13 pull request #592
Opened 2023-02-04 15:54 UTC by Kitsunemitsu

## About The Pull Request
Adds abilities to Bare Metal and Alleyway.

Bare metal now has a small pushback effect on use.
Alleyway now has a teleport slash.

## Why It's Good For The Game
Just increases some ego's fun factor.

## Changelog
:cl:
add: Added abilities to Alleyway and Bare metal
/:cl:

2023-02-05 11:27 UTC, EgorDinamit requested changes
Only WAW and above deserve abilities. Free teleport on a miniature EGO weapon is a bit too much as well.

On the other note - make use of proper cooldown variables instead of constantly using booleans. As is - your weapons have no cooldowns on use and can be effectively spammed.

2023-02-05 11:29 UTC, Kitsunemitsu commented
> Only WAW and above deserve abilities. Free teleport on a miniature EGO weapon is a bit too much as well.
> 
> On the other note - make use of proper cooldown variables instead of constantly using booleans. As is - your weapons have no cooldowns on use and can be effectively spammed.

They have a do-after startup, and the boolean is for turning on and off the teleport ability.

As an aside, almost all EGO right now has an ability of some sort, you just haven't really noticed.
The Teleport also has to hit something, so you are always teleporting into danger, or harming an ally.

2023-02-06 20:55 UTC, Kitsunemitsu commented
Thats what the booleans are for. When you start the spin the bool is set to true. You cannot start another do after if the bool is true

2023-03-04 21:50 UTC, dsmith328 requested changes

2023-03-04 21:50 UTC, dsmith328 commented on code/game/objects/items/ego_weapons/he.dm
> +	if(!do_after(user, 6))
```suggestion
	if(!do_after(user, 6, src))
```
I believe this would fix the issue of duplicate and remove the requirement for "in_use"

2023-03-04 21:50 UTC, dsmith328 commented on code/game/objects/items/ego_weapons/he.dm
> +	if(!do_after(user, 10))
```suggestion
	if(!do_after(user, 10, src))
```
So they can't spam a million bars because it would just look jank

2023-03-13 23:13 UTC, closed without merging