Adds Thunderbird
vlggms/lobotomy-corp13 pull request #621
Opened 2023-02-10 11:03 UTC by vampirebat74

## About The Pull Request

Adds the Thunderbird, an original aberration of Firebird. It provides a similar challenge to the Firebird through an inversion of its mechanics; the abnormality deals additional damage after a good result.

- Raises its qliphoth counter while damaging the employee on a good result
- Prioritizes area denial and slowdowns over raw damage
- Creates thralls from nearby corpses

## Why It's Good For The Game

- Management is more focused on combat and maximizing success rates
- No artificial difficulty through teleportation
- Rewards players for maximizing temperance
- Penalizes careless players who don't read the records
- W Corp. sound effects

## Changelog
:cl:
add: Added new things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

2023-02-12 08:08 UTC, Coxswain-Navigator commented on code/modules/projectiles/projectile/ego_bullets/waw.dm
> +/datum/status_effect/rendRedArmor/on_apply()
Is rendarmor part of thunderbird or remnants of code from something else?

2023-02-12 13:22 UTC, Coxswain-Navigator commented on code/modules/projectiles/projectile/ego_bullets/waw.dm
> +/datum/status_effect/rendRedArmor/on_apply()
I have reason to believe that this is deprecated code from exuviae E.G.O.; get rid of it.

2023-02-12 16:49 UTC, Kitsunemitsu commented on code/modules/projectiles/guns/ego_gun/waw.dm
> +	//firing sound 1
Please add in a special text explaining the weapon

2023-02-12 16:51 UTC, Kitsunemitsu requested changes
Small issues with the EGO weapon. pls fix

2023-02-12 23:35 UTC, Kitsunemitsu commented
Squash commits

2023-02-13 09:14 UTC, vampirebat74 commented
> Small issues with the EGO weapon. pls fix

Is this also concerning the special text?

2023-02-13 21:52 UTC, Kitsunemitsu requested changes
Minor base stat changes. It's too oppressive with all this stuff. Maybe as an aleph

2023-02-13 21:52 UTC, Kitsunemitsu commented on code/modules/mob/living/simple_animal/abnormality/waw/thunder_bird.dm
> +	maxHealth = 2500
Decrease to 1800-2100

2023-02-13 21:52 UTC, Kitsunemitsu commented on code/modules/mob/living/simple_animal/abnormality/waw/thunder_bird.dm
> +	move_to_delay = 3
Increase to 4. It has area denial and a dash that knocks down, it doesn't need to be this fast

2023-02-13 21:52 UTC, Kitsunemitsu commented on code/modules/mob/living/simple_animal/abnormality/waw/thunder_bird.dm
> +	rapid_melee = 3
Reduce to 2, bit too fast, because again, dash and AOE

2023-02-13 22:27 UTC, Kitsunemitsu approved these changes
Tested thoroughly on the server.
Code LGTM

2023-02-13 22:27 UTC, merged