Funeral Visual and Attacks Tweaks
vlggms/lobotomy-corp13 pull request #679
Opened 2023-02-25 02:08 UTC by PotatoTomahto

## About The Pull Request
- Reduced cooldowns and startup time for coffin and gun attacks
- Gun checks for dense turfs in a line instead of view()
- Coffin attack travels in a wave, increased DPS
- Gun sprite telegraph, humans killed by attacks have a cool animation, _h o r i z o n t a l_ coffin
- Code improvement and abnorm behavior changes
- Gift message

## Why It's Good For The Game
Funeral is pretty bad at combat. This PR intends to improve his attacks while also adding more visual flair. If this isn't enough I'll make more drastic changes.

## Changelog
:cl:
tweak: funeral
:cl:

2023-02-25 07:06 UTC, InsightfulParasite commented on code/modules/mob/living/simple_animal/abnormality/he/funeral.dm
> +	retreat_distance = 1
Shouldnt it be the same as minimum distance or else it will walk to minimum and retreat wonkily?

2023-02-26 04:09 UTC, dsmith328 submitted a review, later dismissed
Code looks fine, seems fine in game as well. Overall an improvement

2023-02-26 04:12 UTC, Kitsunemitsu requested changes

2023-02-26 04:12 UTC, Kitsunemitsu commented on code/modules/mob/living/simple_animal/abnormality/_abnormality.dm
> +	GiveTarget(user)
Remove this. out of scope

2023-02-26 04:21 UTC, Kitsunemitsu approved these changes
Changes thoroughly tested. Code looks fine

2023-02-26 04:22 UTC, merged