White Lake tweaks
vlggms/lobotomy-corp13 pull request #681
Opened 2023-02-26 01:52 UTC by Kitsunemitsu

## About The Pull Request
Tweaks white lake.
Chances increased across the board; Having high fort isn't as punishing.
Global white is lessened.
Champion is now until you go sane, and 4/6/6/4 armor instead of 7/9/9/8

## Why It's Good For The Game
White lake was made for a different time. this updates it

## Changelog
:cl:
balance: White Lake Rebalance
/:cl:

2023-02-26 04:17 UTC, dsmith328 commented
Okay my genuine issue with this is WL's ego JUST got a buff for being a "pain in the ass" abno and this is an all around ease up on that. With these changes does Torn Off Wings really justify being a WAW?

2023-02-26 05:11 UTC, Kitsunemitsu commented
We can TM for a bit and see how it goes; the big thing is that the buff now no longer lasts after champ is over.

2023-03-27 05:55 UTC, dsmith328 requested changes

2023-03-27 05:55 UTC, dsmith328 commented on code/modules/mob/living/simple_animal/abnormality/he/white_lake.dm
> -			L.apply_damage(50, WHITE_DAMAGE, null, L.run_armor_check(null, WHITE_DAMAGE), spread_damage = TRUE)
Requesting this damage change reverted and that's it.

2023-03-27 05:57 UTC, dsmith328 approved these changes

2023-03-27 06:01 UTC, merged