Work speed and work chance overrides
vlggms/lobotomy-corp13 pull request #712
Opened 2023-03-07 04:02 UTC by monochromatism

## About The Pull Request

Adds two new procs (and associated variables) to abnormalities to allow them to alter work speed and success chance on the fly. Alters Schadenfreude to use the latter as a sort of demonstration.

## Why It's Good For The Game

More functionality enabling abnormalities to go beyond existing behavioral bounds, allowing both LC-accurate behavior for certain ones (including future ones) and more intricate behavior for those beyond the original LC.

## Changelog
:cl:
code: work speed and chance overrides
/:cl:

2023-03-07 20:24 UTC, monochromatism commented on code/modules/mob/living/simple_animal/abnormality/he/schadenfreude.dm
> -		if(H.z == z && H.stat != DEAD)
Kirie requested it be changed; she is the creator of the abnormality. This enables single-agent runs to not suffer the same consequences as true solo runs.

2023-03-07 20:25 UTC, monochromatism commented on code/game/machinery/computer/abnormality_work.dm
> -			if(do_work(work_chance))
I _could_, but I want the behavior with override set FALSE to be _identical_ to the behavior before the introduction of overrides.

2023-03-09 22:04 UTC, monochromatism commented on code/modules/mob/living/simple_animal/abnormality/he/schadenfreude.dm
> -		if(H.z == z && H.stat != DEAD)
Oh, alright then.

2023-03-13 10:15 UTC, EgorDinamit commented on code/modules/mob/living/simple_animal/abnormality/_abnormality.dm
> +	var/chance_override = FALSE
Obsolete. You don't need these.

2023-03-13 10:16 UTC, EgorDinamit commented on code/modules/mob/living/simple_animal/abnormality/_abnormality.dm
> +/mob/living/simple_animal/hostile/abnormality/proc/SpeedOverride(mob/living/carbon/human/user, work_speed, temp_work_speed, work_type)
```suggestion
/mob/living/simple_animal/hostile/abnormality/proc/SpeedOverride(mob/living/carbon/human/user, work_speed, work_type)
```
We don't need new variable here or anywhere else.

2023-03-13 10:18 UTC, EgorDinamit requested changes
Get rid of "temporary" variables, they are not needed.

2023-03-26 19:03 UTC, dsmith328 requested changes

2023-03-26 19:03 UTC, dsmith328 commented on code/modules/mob/living/simple_animal/abnormality/_abnormality.dm
> +// Overrides the normal work delay. Called in abnormality_work.dm each worktick while speed_override is TRUE.
```suggestion
// Overrides the normal work delay. Called in abnormality_work.dm each worktick.
```

2023-03-29 02:58 UTC, dsmith328 approved these changes

2023-04-03 03:19 UTC, merged