Attempts to remove botany exploits
vlggms/lobotomy-corp13 pull request #727
Opened 2023-03-14 06:53 UTC by PotatoTomahto

## About The Pull Request
- Uranium and plasma mats no longer do their things
- Bamboo recipes removed
- Gaia no more
- Cotton can no longer become durathread
- Slip and bluespace traits removed
- All pyrotechnic recipes no longer exist

## Why It's Good For The Game
Look, botany is fun. I would rather not have to remove every reagent from plants and make mutations impossible. This should solve the biggest issues we've had with botany while also allowing for some hijinks.

## Changelog
:cl:
del: botany and chemistry and mats
:cl:

2023-03-14 08:45 UTC, dsmith328 reviewed
Good notation, TMing first.

2023-03-14 08:54 UTC, EgorDinamit commented on code/modules/hydroponics/grown/random.dm
> -		add_random_reagents(1, 3)
We might keep it if reagents were pulled from a list and not entirely random.

2023-03-14 08:56 UTC, EgorDinamit commented on code/modules/hydroponics/plant_genes.dm
> +//SLIP TRAIT REMOVED
No need to put comments like that.

2023-03-14 08:56 UTC, EgorDinamit commented on code/modules/hydroponics/plant_genes.dm
> +//BLUESPACE TRAIT REMOVED
Ditto.

2023-03-14 08:56 UTC, EgorDinamit commented on lobotomy-corp13.dme
> -#include "code\modules\reagents\chemistry\recipes\pyrotechnics.dm"
Instead of only removing it from .dme, you can delete the file entirely.

2023-03-16 22:14 UTC, out-of-phaze requested changes
Why not blacklist uranium and plasma from metalgen instead, if that's the issue with plasma/uranium plants? Lobotomizing the game by removing banana slipping, material effects, random reagents (instead of blacklisting problem chems, which *already exists*), and *every single pyrotechnic reaction* to fix issues with a fundamentally broken system with a *lot* of griefing potential beyond what you've already removed here is a bad idea. The argument that some of these things don't belong anyway doesn't pass muster, because the same applies to a lot of botany itself, like mutations, and if you were removing this stuff for not making sense in the setting you went about it the wrong way anyway.

A much better solution, I think, would be to keep the parts of botany that people like—from asking around, that seems to mostly just be growing food—and remove the parts that cause issues, like mutations and splicing. For plants available via mutation that are still desirable, like meatwheat, alternate methods of acquiring them could be added.

2023-03-16 22:14 UTC, out-of-phaze commented on code/modules/hydroponics/hydroponics_chemreact.dm
> +		if(0 to 10)
This line probably has a merge conflict now, since it was changed in the linter PR.

2023-03-19 18:19 UTC, Gboster-0 commented
> Blue-tomatoes still have space lube, and can therefore be used in slips. Liquid contents still exists, and can therefore be combined (via secateurs) with any plant containing a hazardous chemical to devastating results (against humans). Death-nettles still exist, and are rather nasty weapons (they do damage comparable to energy swords on other servers, though it's halved every time you hit someone) you can carry a hundred of in a plant bag. I do not see why Gaia was removed.

blue tomatoes and nettles were removed several months ago, before botany was seen.
About liquid contents... you can just use a normal EGO weapon to much more devastating effects if you are going to grief. believe me nobody wants to bother doing something for an hour to grief with medium efficiency if you can do the same in 10 minutes with high efficiency

2023-04-06 00:32 UTC, dsmith328 approved these changes
This should be re-reviewed and replaced with better changes later. Merging because of actual issues this solves.

2023-04-06 00:35 UTC, merged