[COMMISSION] A Quiet Day
vlggms/lobotomy-corp13 pull request #770
Opened 2023-03-22 06:48 UTC by Kitsunemitsu

Adds A Quiet Day

## About The Pull Request
Adds a new Zayin, A Quiet Day.
After you finish work on it, it goes on a short rant (45-60 seconds) and then gives you a buff for the work type you do, so long as you stay in the room.
During the rant no work can be done.

## Why It's Good For The Game
This is a zayin I see used more into the lategame, but if the buff is too powerful I can reduce it to +10 instead of +15

## Changelog
:cl:
add: Added A Quiet Day
/:cl:

2023-03-22 21:03 UTC, dsmith328 commented on code/modules/mob/living/simple_animal/abnormality/zayin/quietday.dm
> +	var/listener
Unused variable.

2023-03-22 21:03 UTC, dsmith328 commented on code/modules/mob/living/simple_animal/abnormality/zayin/quietday.dm
> +	if(!(user in view(5, src)))
Should probably make this check _while talking_ as opposed to after, as you could just leave and come back before it's done.

2023-03-22 21:03 UTC, dsmith328 commented on code/modules/mob/living/simple_animal/abnormality/zayin/quietday.dm
I see nothing in this stopping work from being done while it's talking, at least not at the moment. If this is a WIP please make it a draft.

2023-03-22 21:08 UTC, Kitsunemitsu commented on code/modules/mob/living/simple_animal/abnormality/zayin/quietday.dm
Talk start calls sleeps before Postwork effect can finish, delaying the ability to work until talk end is called.

2023-03-25 20:11 UTC, dsmith328 requested changes

2023-03-25 20:11 UTC, dsmith328 commented on code/modules/mob/living/simple_animal/abnormality/zayin/quietday.dm
> +				if(PlayerCheck(user) == TRUE)
Make PlayerCheck return False outside of the `if` statements and change these to just `if(PlayerCheck(user))` please

2023-03-25 20:11 UTC, dsmith328 commented on code/modules/mob/living/simple_animal/abnormality/zayin/quietday.dm
> +	attribute_buff =JUSTICE_ATTRIBUTE
```suggestion
	attribute_buff = JUSTICE_ATTRIBUTE
```

2023-04-03 06:41 UTC, Coxswain-Navigator commented on code/modules/paperwork/records/info/zayin.dm
> +	abno_code = "T-01-144"
Theonite slab was recently merged with this abno code, it will need to be changed. 145 should be fine.

2023-04-04 21:27 UTC, dsmith328 approved these changes

2023-04-04 21:28 UTC, merged