[COMMISSION] Adds Til the Last Shot
vlggms/lobotomy-corp13 pull request #827
Opened 2023-04-08 10:16 UTC by Kitsunemitsu

## About The Pull Request
Adds 'Til the Last Shot, a spreading meat abnormality.
https://media.discordapp.net/attachments/692322841747652718/1093679726834503680/image.png

Still needs:
EGO
Records

## Changelog
:cl:
add: Added Til the Last Shot
/:cl:

2023-04-26 05:13 UTC, Coxswain-Navigator reviewed
Nothing strikes me as fundamentally flawed, I would like to see it finished.

2023-08-03 23:04 UTC, JackFrost2424 commented
From the test we did last round: 
>Meatvines have been proven to basically be hard to break even with high damage weapons. Might be intentional but considering how annoying they are, might not be a good idea 
>14 boxes? Kinda weird for a HE of all things. I would at least make it 16-18. 
>I would drastically reduce the HP of the meatmen. Maybe to 250-300.  And lower the damage accordingly. Considering how quickly they can spawn. Make the projectile do 20 and make their melee have 10 at the low end.
>EGO is fine if the other changes were done.

2023-08-07 02:53 UTC, LanceSmites328 requested changes

2023-08-07 02:53 UTC, LanceSmites328 commented on code/modules/paperwork/records/info/aleph.dm
> +		"When the Qliphtoh Counter reached 0, last shot bred flesh until it was destroyed in it's containment.")
Does not mention high temperance reducing success chance. While it seems redundant, the Justice and Fortitude requirements should be stated on two separate lines to indicate their stacking nature.
```suggestion
	abno_info = list(
		"Employees with low Temperance had their work chance increased dramatically.",
		"Employees with high Temperance had their work chance reduced dramatically.",
		"Employees with Fortitude under level 5 received more work damage.",
		"Employees with Justice under level 5 received more work damage.",
		"When the work result was Bad, the Qliphoth Counter lowered.",
		"When the Qliphtoh Counter reached 0, last shot bred flesh until it was destroyed in it's containment.")
```

2023-08-08 21:53 UTC, LanceSmites328 requested changes

2023-08-08 21:53 UTC, LanceSmites328 commented on code/modules/paperwork/records/info/aleph.dm
> +		"Employees with high Temperance had their work chance reduced dramatically.",
```suggestion
		"Employees with Temperance levels below 4 had their work chance increased dramatically.",
		"Employees with Temperance levels 5 and above had their work chance reduced dramatically.",
```

2023-08-08 21:54 UTC, LanceSmites328 approved these changes

2023-08-09 00:00 UTC, merged