Adds Someone's Portrait
vlggms/lobotomy-corp13 pull request #909
Opened 2023-05-05 07:11 UTC by Coxswain-Navigator

## About The Pull Request
Adds a new TETH abnormality.

- When the user's fortitude and prudence are 1, the work automatically ends in failure.
- If the work attempt was a failure, the user panics.
- The user may(WILL!) experience hallucinations during work.

## Why It's Good For The Game
Its cool I guess. Also beam gun.

## Changelog
:cl:
add: Added Someone's Portrait
/:cl:

2023-05-05 07:18 UTC, Coxswain-Navigator commented
E.G.O. sprites are temporary. May do them myself later.

2023-05-05 18:24 UTC, dsmith328 requested changes

2023-05-05 18:24 UTC, dsmith328 commented on code/modules/mob/living/simple_animal/abnormality/teth/someonesportrait.dm
> +		H.ai_controller = /datum/ai_controller/insane/wander
Please add code here to add the Wander Panic status effect to show the correct halo

2023-05-18 06:01 UTC, Kitsunemitsu approved these changes
Code Looks good, testing was pretty great

2023-05-18 06:03 UTC, merged