Little Red Riding Hooded Mercenary
vlggms/lobotomy-corp13 pull request #920
Opened 2023-05-09 05:05 UTC by monochromatism

## About The Pull Request

Adds Little Red Riding Hooded Mercenary. You know who she is.

She comes with the following:
- Powerful... power generation... abilities.
- Solid EGO. Very fun to use.
- EXTREMELY interactive in playable abnormalities, including player UI cues for what the AI-controlled abnormality has as automatic behavior.
- Unique dynamic with Reddened Buddy and Blue Smocked Shepherd. (May be buggy, this was *exceptionally* messy to code.)

Please keep in mind that all her specific numbers (damage values, HP thresholds, cooldowns, etc.) are subject to change; it's hard to get a concept of exactly how strong she is, aside from that she can consistently beat Blue Smocked Shepherd and Reddened Buddy in combat. They're all modular and prepared for quick changes, however.

## Why It's Good For The Game

See above. More abnormalities. Completing a contribution to Abno Jam of May 2023. Adds something unique to the current dynamic. Shouldn't be too hard to code Wolf interactivity, if and when Big and Will Be Bad Wolf arrives.

## Changelog
:cl:
add: Little Red Riding Hooded Mercenary
/:cl:

2023-06-11 13:01 UTC, dsmith328 requested changes

2023-06-11 13:01 UTC, dsmith328 commented on code/modules/mob/living/simple_animal/abnormality/he/blue_shepherd.dm
> +				current_red.WatchIt()
I'd have an issue with this if it was a WAW vs an HE, honestly.

2023-06-11 13:01 UTC, dsmith328 commented on code/modules/mob/living/simple_animal/abnormality/waw/red_riding_mercenary.dm
> +		)
TLDR; She's swol and doesn't need these boosts. Her utility pays for it in droves.

2023-09-02 22:36 UTC, LanceSmites328 commented
This PR has had changes requested to it for **4 Months** and nothing has been done. If this has not been addressed in the next 3 days I'll be closing this PR and giving someone else a chance to take over this abnormality.

2023-09-05 18:04 UTC, LanceSmites328 commented
Marking as stale and closing PR.

2023-09-05 18:04 UTC, closed without merging