Lambda Corp
vlggms/lobotomy-corp13 pull request #934
Opened 2023-05-13 01:09 UTC by ScarSkit

## About The Pull Request

Adds Lambda Corp in the game

## Why It's Good For The Game

THE MORE MAPS THE MERRIER. Also uses disposals as its gimmick

## Changelog
:cl:
add: Added Lambda Corp
/:cl:

2023-06-26 19:28 UTC, Kitsunemitsu requested changes

2023-06-26 19:28 UTC, Kitsunemitsu commented on _maps/lambdacorp.json
> +	"map_name": "Facility k-909",
Capitalize the K and I'll merge.

2023-06-26 20:34 UTC, ScarSkit commented
Ok

On Mon, Jun 26, 2023, 3:28 PM Kirie Saito ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In _maps/lambdacorp.json
> <https://github.com/vlggms/lobotomy-corp13/pull/934#discussion_r1242666374>
> :
>
> > @@ -0,0 +1,15 @@
> +{
> +	"version": 1,
> +	"map_name": "Facility k-909",
>
> Capitalize the K and I'll merge.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/vlggms/lobotomy-corp13/pull/934#pullrequestreview-1499265033>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A4HTNHD7EBZGEJY57USSCIDXNHPF3ANCNFSM6AAAAAAYAE4ZRM>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-07-08 21:29 UTC, Kitsunemitsu approved these changes
Yeah I actually really like this map. we'll see how the community likes it.

2023-07-13 01:33 UTC, merged