Remove unused vars/procs in LC13 code
vlggms/lobotomy-corp13 pull request #949
Opened 2023-05-15 12:38 UTC by out-of-phaze

## About The Pull Request
Removes a lot of unused vars and procs in LC13-specific code.

## Why It's Good For The Game
Like #948 but bigger. Specifically excludes the changes made in that PR. Shouldn't affect functionality because none of this is used. If you'd like me to change how I used or removed some vars please tell me.

2023-05-15 18:21 UTC, Kitsunemitsu requested changes
Couple things I likely am still using either right now, or in the very near future regarding refinery.

2023-05-15 18:21 UTC, Kitsunemitsu commented on ModularTegustation/tegu_items/lc13/refinery/sales.dm
> -	var/icon_full = "machinelcb_full"
If I ever design a different machine frame I will still need this.

2023-05-15 18:21 UTC, Kitsunemitsu commented on code/game/objects/items/ego_weapons/non_abnormality/cane.dm
> -	var/activated
Leave this one in, These weapons were originally going to have a buff applied (and thus I would need to know if it was applied), and if I ever get around to it, they will in the future

2023-05-15 18:21 UTC, Kitsunemitsu commented on code/modules/mob/living/simple_animal/abnormality/he/der_freischutz.dm
> +// currently unused, TODO: use or remove
Admeme proc.

2023-06-24 09:55 UTC, EgorDinamit commented
The conflicts!

2023-06-25 02:47 UTC, out-of-phaze commented
> The conflicts!

There weren't any cornflakes a month ago when I requested a review :v

2023-09-24 19:54 UTC, Kitsunemitsu commented
Stale, if you want to reopen, please do.

2023-09-24 19:54 UTC, closed without merging