Changes to understanding and rolling
vlggms/lobotomy-corp13 pull request #964
Opened 2023-05-18 18:31 UTC by Skryty-cmd

This pull request is some changes kirie said i could do.

This includes changes that are supposed to promote yellow rolling as well as picking less-liked abnos and also promotes maxing out understanding.

CHANGES:
-Game time no longer gives you respawn stats, instead each 5 fully understood abnos give you increased stats (this might need to be adjusted, waiting on feedback!!)
-Yellow rolling / red rolling awards 250 PE boxes

TO BE DONE:
Abnormality pick and 100% understanding count is saved in a persistent file, for both developer analysis and later use Abnormalities that are picked less will automatically reward you somehow for picking them.

2023-05-18 18:38 UTC, Kitsunemitsu requested changes
Very minor changes.

2023-05-18 18:38 UTC, Kitsunemitsu commented on code/datums/abnormality/datum/abnormality.dm
> +			SSlobotomy_corp.understood_abnos += current
Use |= insteas of +=, the former checks if it's already in the list.

2023-05-18 18:38 UTC, Kitsunemitsu commented on code/game/machinery/computer/abnormality_queue.dm
> +		// PE awarded for yellow roll - just as kirie had wanted.
Add a little chat message for this, something like "Headquarters has reimbursed you the cost of extracting a specific abnormality"

2023-05-18 18:38 UTC, Kitsunemitsu commented on code/modules/jobs/job_types/agent.dm
> +	// see this system? FUCK your time stats. FUCK you! UNDERSTANDING OVER ALL! SHOVEL CONQUERS ALL!
Can you make this a %based thing soon? Every 20% of total abnos?

2023-05-18 20:55 UTC, Kitsunemitsu commented
I am personally approving this design wise.
I want this for a few reasons.

1) I want to encourage players to be more varied in which abnormalities they pick.
2) I want to encourage randomness in gameplay.
3) I want agents to work on all abnormalities, not just whatever meta ones they happen to have, ignoring all the others.

2023-05-18 22:37 UTC, TravisAngeI commented
maybe a way to reward players for picking less-picked abnos is a lower meltdown chance per meltdown? idk how that would work but its an idea

2023-05-19 00:36 UTC, Kitsunemitsu commented on code/modules/jobs/job_types/agent.dm
> +			set_attribute *= 4
I fixed this.

2023-05-19 08:47 UTC, Tokanova commented
biggest issue atm with this is basic gameplay of lob corp does not lead to 100% understanding
you do a little of this and that just to finish getting armor and then move on to the next abnormality which is more difficult than the last
so round start agents get training through this ladder but late joins get nothing because no one is going to  grind out the teths and zayins because that's a waste and ordeals will just pop off and kill the agents because they don't have enough good gear.

2023-05-19 09:03 UTC, Kitsunemitsu commented
> maybe a way to reward players for picking less-picked abnos is a lower meltdown chance per meltdown? idk how that would work but its an idea
> 
> basically abnos are less likely to melt than others

Its coming but as a reward for picking abnos not usually picked.

2023-05-19 09:04 UTC, Kitsunemitsu commented
Change pr name and desc and I'll get it merged.

2023-05-21 21:03 UTC, Kitsunemitsu approved these changes
Looks good to me, will enable again after I get around to it.

2023-05-21 21:03 UTC, merged