Adds puss in boots
vlggms/lobotomy-corp13 pull request #986
Opened 2023-05-23 10:32 UTC by Coxswain-Navigator

## About The Pull Request
Clerk lover abnormality.

- Blesses agents that are level 1 who pet it.
- Blessed agent gains .2 defense to all damage types, and additional attributes scaling with respawn attributes.
- Blessed agent also receives a special lance-type weapon only they can use.
- Puss in boots will perform a friendly breach when its qlipthoth counter reaches 0 and someone is blessed.
- Puss in boots's qliphoth counter goes down every time a different abnormality breaches.
- If the blessed agent performs work, panics, or dies, puss in boots will breach, teleporting to their location if they are alive.
Also fixes a runtime related to lances
Adds a new "special" E.G.O. folder and moves training weapons into it

## Why It's Good For The Game
Clerks need some love

## Changelog
:cl:
add: Added puss in boots
/:cl:

2023-05-26 03:54 UTC, dsmith328 requested changes

2023-05-26 03:54 UTC, dsmith328 commented on code/modules/mob/living/simple_animal/abnormality/he/puss_in_boots.dm
> +			H.gib() //maybe we can get a special gib effect for cutting someone in half someday.
```Suggestion
/mob/living/simple_animal/hostile/abnormality/puss_in_boots/proc/Finisher(mob/living/target)
	target.apply_damage(50, PALE_DAMAGE, null, target.run_armor_check(null, RED_DAMAGE)) //50% of your health in red damage
	to_chat(target,"<span class='danger'>[src] is trying to cut you in half!</span>")
	if(!ishuman(target))
		return
	if(target.health >= 0)
		return
	var/mob/living/carbon/human/H = target
	H.gib() //maybe we can get a special gib effect for cutting someone in half someday.
```
For readability.

2023-05-26 03:54 UTC, dsmith328 commented on code/modules/mob/living/simple_animal/abnormality/he/puss_in_boots.dm
> +	return ..()
This is a LOT of resistance on top of them now being able to wear EGO armor AND it's not the same when removed. (Becomes 80% resistance on application, removal becomes 33.4% resistance.)

2023-05-26 03:54 UTC, dsmith328 commented on code/modules/mob/living/simple_animal/abnormality/he/puss_in_boots.dm
> +	var/turf/home = null
Unused
```suggestion
```

2023-05-26 03:54 UTC, dsmith328 commented on code/modules/mob/living/simple_animal/abnormality/he/puss_in_boots.dm
> +#define STATUS_EFFECT_CHOSEN /datum/status_effect/chosen
Defined but definition is unused, or otherwise missing in some places.

2023-05-26 03:54 UTC, dsmith328 commented on code/modules/paperwork/records/info/he.dm
> +	abno_can_breach = TRUE
I believe this is unneeded?

2023-06-25 08:57 UTC, dsmith328 approved these changes

2023-07-01 02:08 UTC, dsmith328 reviewed
Fix conflicts and ping me

2023-07-03 21:55 UTC, LanceSmites328 approved these changes

2023-07-03 21:55 UTC, merged